// Code generated by ent, DO NOT EDIT.

package upstream

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstream type in the database.
	Label = "upstream"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSortCode holds the string denoting the sort_code field in the database.
	FieldSortCode = "sort_code"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldTokenEncrypted holds the string denoting the token_encrypted field in the database.
	FieldTokenEncrypted = "token_encrypted"
	// FieldRefreshTokenEncrypted holds the string denoting the refresh_token_encrypted field in the database.
	FieldRefreshTokenEncrypted = "refresh_token_encrypted"
	// FieldPasswordEncrypted holds the string denoting the password_encrypted field in the database.
	FieldPasswordEncrypted = "password_encrypted"
	// FieldTokenExpiresAt holds the string denoting the token_expires_at field in the database.
	FieldTokenExpiresAt = "token_expires_at"
	// FieldLoginIdentifier holds the string denoting the login_identifier field in the database.
	FieldLoginIdentifier = "login_identifier"
	// FieldRemoteUserID holds the string denoting the remote_user_id field in the database.
	FieldRemoteUserID = "remote_user_id"
	// FieldBalanceSnapshot holds the string denoting the balance_snapshot field in the database.
	FieldBalanceSnapshot = "balance_snapshot"
	// FieldGroupSnapshot holds the string denoting the group_snapshot field in the database.
	FieldGroupSnapshot = "group_snapshot"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// Table holds the table name of the upstream in the database.
	Table = "upstreams"
)

// Columns holds all SQL columns for upstream fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSortCode,
	FieldKind,
	FieldBaseURL,
	FieldTokenEncrypted,
	FieldRefreshTokenEncrypted,
	FieldPasswordEncrypted,
	FieldTokenExpiresAt,
	FieldLoginIdentifier,
	FieldRemoteUserID,
	FieldBalanceSnapshot,
	FieldGroupSnapshot,
	FieldNotes,
	FieldEnabled,
	FieldLastCheckedAt,
	FieldLastError,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultSortCode holds the default value on creation for the "sort_code" field.
	DefaultSortCode int
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// LoginIdentifierValidator is a validator for the "login_identifier" field. It is called by the builders before save.
	LoginIdentifierValidator func(string) error
	// RemoteUserIDValidator is a validator for the "remote_user_id" field. It is called by the builders before save.
	RemoteUserIDValidator func(string) error
	// DefaultBalanceSnapshot holds the default value on creation for the "balance_snapshot" field.
	DefaultBalanceSnapshot map[string]interface{}
	// DefaultGroupSnapshot holds the default value on creation for the "group_snapshot" field.
	DefaultGroupSnapshot map[string]interface{}
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the Upstream queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySortCode orders the results by the sort_code field.
func BySortCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortCode, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByTokenEncrypted orders the results by the token_encrypted field.
func ByTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenEncrypted, opts...).ToFunc()
}

// ByRefreshTokenEncrypted orders the results by the refresh_token_encrypted field.
func ByRefreshTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenEncrypted, opts...).ToFunc()
}

// ByPasswordEncrypted orders the results by the password_encrypted field.
func ByPasswordEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordEncrypted, opts...).ToFunc()
}

// ByTokenExpiresAt orders the results by the token_expires_at field.
func ByTokenExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenExpiresAt, opts...).ToFunc()
}

// ByLoginIdentifier orders the results by the login_identifier field.
func ByLoginIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginIdentifier, opts...).ToFunc()
}

// ByRemoteUserID orders the results by the remote_user_id field.
func ByRemoteUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteUserID, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}
