// Code generated by ent, DO NOT EDIT.

package upstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// SortCode applies equality check predicate on the "sort_code" field. It's identical to SortCodeEQ.
func SortCode(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldSortCode, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldKind, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// TokenEncrypted applies equality check predicate on the "token_encrypted" field. It's identical to TokenEncryptedEQ.
func TokenEncrypted(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldTokenEncrypted, v))
}

// RefreshTokenEncrypted applies equality check predicate on the "refresh_token_encrypted" field. It's identical to RefreshTokenEncryptedEQ.
func RefreshTokenEncrypted(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// PasswordEncrypted applies equality check predicate on the "password_encrypted" field. It's identical to PasswordEncryptedEQ.
func PasswordEncrypted(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// LoginIdentifier applies equality check predicate on the "login_identifier" field. It's identical to LoginIdentifierEQ.
func LoginIdentifier(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLoginIdentifier, v))
}

// RemoteUserID applies equality check predicate on the "remote_user_id" field. It's identical to RemoteUserIDEQ.
func RemoteUserID(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRemoteUserID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldNotes, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldEnabled, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastError, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldName, v))
}

// SortCodeEQ applies the EQ predicate on the "sort_code" field.
func SortCodeEQ(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldSortCode, v))
}

// SortCodeNEQ applies the NEQ predicate on the "sort_code" field.
func SortCodeNEQ(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldSortCode, v))
}

// SortCodeIn applies the In predicate on the "sort_code" field.
func SortCodeIn(vs ...int) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldSortCode, vs...))
}

// SortCodeNotIn applies the NotIn predicate on the "sort_code" field.
func SortCodeNotIn(vs ...int) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldSortCode, vs...))
}

// SortCodeGT applies the GT predicate on the "sort_code" field.
func SortCodeGT(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldSortCode, v))
}

// SortCodeGTE applies the GTE predicate on the "sort_code" field.
func SortCodeGTE(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldSortCode, v))
}

// SortCodeLT applies the LT predicate on the "sort_code" field.
func SortCodeLT(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldSortCode, v))
}

// SortCodeLTE applies the LTE predicate on the "sort_code" field.
func SortCodeLTE(v int) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldSortCode, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldKind, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldBaseURL, v))
}

// TokenEncryptedEQ applies the EQ predicate on the "token_encrypted" field.
func TokenEncryptedEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedNEQ applies the NEQ predicate on the "token_encrypted" field.
func TokenEncryptedNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedIn applies the In predicate on the "token_encrypted" field.
func TokenEncryptedIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedNotIn applies the NotIn predicate on the "token_encrypted" field.
func TokenEncryptedNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedGT applies the GT predicate on the "token_encrypted" field.
func TokenEncryptedGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldTokenEncrypted, v))
}

// TokenEncryptedGTE applies the GTE predicate on the "token_encrypted" field.
func TokenEncryptedGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldTokenEncrypted, v))
}

// TokenEncryptedLT applies the LT predicate on the "token_encrypted" field.
func TokenEncryptedLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldTokenEncrypted, v))
}

// TokenEncryptedLTE applies the LTE predicate on the "token_encrypted" field.
func TokenEncryptedLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldTokenEncrypted, v))
}

// TokenEncryptedContains applies the Contains predicate on the "token_encrypted" field.
func TokenEncryptedContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldTokenEncrypted, v))
}

// TokenEncryptedHasPrefix applies the HasPrefix predicate on the "token_encrypted" field.
func TokenEncryptedHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldTokenEncrypted, v))
}

// TokenEncryptedHasSuffix applies the HasSuffix predicate on the "token_encrypted" field.
func TokenEncryptedHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldTokenEncrypted, v))
}

// TokenEncryptedEqualFold applies the EqualFold predicate on the "token_encrypted" field.
func TokenEncryptedEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldTokenEncrypted, v))
}

// TokenEncryptedContainsFold applies the ContainsFold predicate on the "token_encrypted" field.
func TokenEncryptedContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldTokenEncrypted, v))
}

// RefreshTokenEncryptedEQ applies the EQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedNEQ applies the NEQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIn applies the In predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedNotIn applies the NotIn predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedGT applies the GT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedGTE applies the GTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLT applies the LT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLTE applies the LTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContains applies the Contains predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasPrefix applies the HasPrefix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasSuffix applies the HasSuffix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIsNil applies the IsNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedNotNil applies the NotNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedEqualFold applies the EqualFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContainsFold applies the ContainsFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldRefreshTokenEncrypted, v))
}

// PasswordEncryptedEQ applies the EQ predicate on the "password_encrypted" field.
func PasswordEncryptedEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedNEQ applies the NEQ predicate on the "password_encrypted" field.
func PasswordEncryptedNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIn applies the In predicate on the "password_encrypted" field.
func PasswordEncryptedIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedNotIn applies the NotIn predicate on the "password_encrypted" field.
func PasswordEncryptedNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedGT applies the GT predicate on the "password_encrypted" field.
func PasswordEncryptedGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedGTE applies the GTE predicate on the "password_encrypted" field.
func PasswordEncryptedGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLT applies the LT predicate on the "password_encrypted" field.
func PasswordEncryptedLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLTE applies the LTE predicate on the "password_encrypted" field.
func PasswordEncryptedLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContains applies the Contains predicate on the "password_encrypted" field.
func PasswordEncryptedContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasPrefix applies the HasPrefix predicate on the "password_encrypted" field.
func PasswordEncryptedHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasSuffix applies the HasSuffix predicate on the "password_encrypted" field.
func PasswordEncryptedHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIsNil applies the IsNil predicate on the "password_encrypted" field.
func PasswordEncryptedIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldPasswordEncrypted))
}

// PasswordEncryptedNotNil applies the NotNil predicate on the "password_encrypted" field.
func PasswordEncryptedNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldPasswordEncrypted))
}

// PasswordEncryptedEqualFold applies the EqualFold predicate on the "password_encrypted" field.
func PasswordEncryptedEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContainsFold applies the ContainsFold predicate on the "password_encrypted" field.
func PasswordEncryptedContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldPasswordEncrypted, v))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldTokenExpiresAt))
}

// LoginIdentifierEQ applies the EQ predicate on the "login_identifier" field.
func LoginIdentifierEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLoginIdentifier, v))
}

// LoginIdentifierNEQ applies the NEQ predicate on the "login_identifier" field.
func LoginIdentifierNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLoginIdentifier, v))
}

// LoginIdentifierIn applies the In predicate on the "login_identifier" field.
func LoginIdentifierIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLoginIdentifier, vs...))
}

// LoginIdentifierNotIn applies the NotIn predicate on the "login_identifier" field.
func LoginIdentifierNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLoginIdentifier, vs...))
}

// LoginIdentifierGT applies the GT predicate on the "login_identifier" field.
func LoginIdentifierGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLoginIdentifier, v))
}

// LoginIdentifierGTE applies the GTE predicate on the "login_identifier" field.
func LoginIdentifierGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLoginIdentifier, v))
}

// LoginIdentifierLT applies the LT predicate on the "login_identifier" field.
func LoginIdentifierLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLoginIdentifier, v))
}

// LoginIdentifierLTE applies the LTE predicate on the "login_identifier" field.
func LoginIdentifierLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLoginIdentifier, v))
}

// LoginIdentifierContains applies the Contains predicate on the "login_identifier" field.
func LoginIdentifierContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldLoginIdentifier, v))
}

// LoginIdentifierHasPrefix applies the HasPrefix predicate on the "login_identifier" field.
func LoginIdentifierHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldLoginIdentifier, v))
}

// LoginIdentifierHasSuffix applies the HasSuffix predicate on the "login_identifier" field.
func LoginIdentifierHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldLoginIdentifier, v))
}

// LoginIdentifierIsNil applies the IsNil predicate on the "login_identifier" field.
func LoginIdentifierIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLoginIdentifier))
}

// LoginIdentifierNotNil applies the NotNil predicate on the "login_identifier" field.
func LoginIdentifierNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLoginIdentifier))
}

// LoginIdentifierEqualFold applies the EqualFold predicate on the "login_identifier" field.
func LoginIdentifierEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldLoginIdentifier, v))
}

// LoginIdentifierContainsFold applies the ContainsFold predicate on the "login_identifier" field.
func LoginIdentifierContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldLoginIdentifier, v))
}

// RemoteUserIDEQ applies the EQ predicate on the "remote_user_id" field.
func RemoteUserIDEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldRemoteUserID, v))
}

// RemoteUserIDNEQ applies the NEQ predicate on the "remote_user_id" field.
func RemoteUserIDNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldRemoteUserID, v))
}

// RemoteUserIDIn applies the In predicate on the "remote_user_id" field.
func RemoteUserIDIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldRemoteUserID, vs...))
}

// RemoteUserIDNotIn applies the NotIn predicate on the "remote_user_id" field.
func RemoteUserIDNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldRemoteUserID, vs...))
}

// RemoteUserIDGT applies the GT predicate on the "remote_user_id" field.
func RemoteUserIDGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldRemoteUserID, v))
}

// RemoteUserIDGTE applies the GTE predicate on the "remote_user_id" field.
func RemoteUserIDGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldRemoteUserID, v))
}

// RemoteUserIDLT applies the LT predicate on the "remote_user_id" field.
func RemoteUserIDLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldRemoteUserID, v))
}

// RemoteUserIDLTE applies the LTE predicate on the "remote_user_id" field.
func RemoteUserIDLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldRemoteUserID, v))
}

// RemoteUserIDContains applies the Contains predicate on the "remote_user_id" field.
func RemoteUserIDContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldRemoteUserID, v))
}

// RemoteUserIDHasPrefix applies the HasPrefix predicate on the "remote_user_id" field.
func RemoteUserIDHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldRemoteUserID, v))
}

// RemoteUserIDHasSuffix applies the HasSuffix predicate on the "remote_user_id" field.
func RemoteUserIDHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldRemoteUserID, v))
}

// RemoteUserIDIsNil applies the IsNil predicate on the "remote_user_id" field.
func RemoteUserIDIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldRemoteUserID))
}

// RemoteUserIDNotNil applies the NotNil predicate on the "remote_user_id" field.
func RemoteUserIDNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldRemoteUserID))
}

// RemoteUserIDEqualFold applies the EqualFold predicate on the "remote_user_id" field.
func RemoteUserIDEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldRemoteUserID, v))
}

// RemoteUserIDContainsFold applies the ContainsFold predicate on the "remote_user_id" field.
func RemoteUserIDContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldRemoteUserID, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldNotes, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldEnabled, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLastCheckedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.NotPredicates(p))
}
