// Code generated by ent, DO NOT EDIT.

package upstreamresourceaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldID, id))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldResourceID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldPlatform, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldAccountID, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldRateMultiplier, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldSyncedAt, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldResourceID, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldContainsFold(FieldPlatform, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldAccountID, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldRateMultiplier, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.FieldLTE(FieldSyncedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamResourceAccount) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamResourceAccount) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamResourceAccount) predicate.UpstreamResourceAccount {
	return predicate.UpstreamResourceAccount(sql.NotPredicates(p))
}
