// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresourceaccount"
)

// UpstreamResourceAccountCreate is the builder for creating a UpstreamResourceAccount entity.
type UpstreamResourceAccountCreate struct {
	config
	mutation *UpstreamResourceAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResourceID sets the "resource_id" field.
func (_c *UpstreamResourceAccountCreate) SetResourceID(v int64) *UpstreamResourceAccountCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UpstreamResourceAccountCreate) SetPlatform(v string) *UpstreamResourceAccountCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UpstreamResourceAccountCreate) SetAccountID(v int64) *UpstreamResourceAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *UpstreamResourceAccountCreate) SetRateMultiplier(v float64) *UpstreamResourceAccountCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *UpstreamResourceAccountCreate) SetSyncedAt(v time.Time) *UpstreamResourceAccountCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// Mutation returns the UpstreamResourceAccountMutation object of the builder.
func (_c *UpstreamResourceAccountCreate) Mutation() *UpstreamResourceAccountMutation {
	return _c.mutation
}

// Save creates the UpstreamResourceAccount in the database.
func (_c *UpstreamResourceAccountCreate) Save(ctx context.Context) (*UpstreamResourceAccount, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamResourceAccountCreate) SaveX(ctx context.Context) *UpstreamResourceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamResourceAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamResourceAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamResourceAccountCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "UpstreamResourceAccount.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := upstreamresourceaccount.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "UpstreamResourceAccount.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := upstreamresourceaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UpstreamResourceAccount.account_id"`)}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := upstreamresourceaccount.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "UpstreamResourceAccount.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "UpstreamResourceAccount.synced_at"`)}
	}
	return nil
}

func (_c *UpstreamResourceAccountCreate) sqlSave(ctx context.Context) (*UpstreamResourceAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamResourceAccountCreate) createSpec() (*UpstreamResourceAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamResourceAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamresourceaccount.Table, sqlgraph.NewFieldSpec(upstreamresourceaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(upstreamresourceaccount.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(upstreamresourceaccount.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresourceaccount.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamResourceAccount.Create().
//		SetResourceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamResourceAccountUpsert) {
//			SetResourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamResourceAccountCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamResourceAccountUpsertOne {
	_c.conflict = opts
	return &UpstreamResourceAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamResourceAccountCreate) OnConflictColumns(columns ...string) *UpstreamResourceAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamResourceAccountUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamResourceAccountUpsertOne is the builder for "upsert"-ing
	//  one UpstreamResourceAccount node.
	UpstreamResourceAccountUpsertOne struct {
		create *UpstreamResourceAccountCreate
	}

	// UpstreamResourceAccountUpsert is the "OnConflict" setter.
	UpstreamResourceAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetResourceID sets the "resource_id" field.
func (u *UpstreamResourceAccountUpsert) SetResourceID(v int64) *UpstreamResourceAccountUpsert {
	u.Set(upstreamresourceaccount.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsert) UpdateResourceID() *UpstreamResourceAccountUpsert {
	u.SetExcluded(upstreamresourceaccount.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *UpstreamResourceAccountUpsert) AddResourceID(v int64) *UpstreamResourceAccountUpsert {
	u.Add(upstreamresourceaccount.FieldResourceID, v)
	return u
}

// SetPlatform sets the "platform" field.
func (u *UpstreamResourceAccountUpsert) SetPlatform(v string) *UpstreamResourceAccountUpsert {
	u.Set(upstreamresourceaccount.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsert) UpdatePlatform() *UpstreamResourceAccountUpsert {
	u.SetExcluded(upstreamresourceaccount.FieldPlatform)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamResourceAccountUpsert) SetAccountID(v int64) *UpstreamResourceAccountUpsert {
	u.Set(upstreamresourceaccount.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsert) UpdateAccountID() *UpstreamResourceAccountUpsert {
	u.SetExcluded(upstreamresourceaccount.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamResourceAccountUpsert) AddAccountID(v int64) *UpstreamResourceAccountUpsert {
	u.Add(upstreamresourceaccount.FieldAccountID, v)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsert) SetRateMultiplier(v float64) *UpstreamResourceAccountUpsert {
	u.Set(upstreamresourceaccount.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsert) UpdateRateMultiplier() *UpstreamResourceAccountUpsert {
	u.SetExcluded(upstreamresourceaccount.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsert) AddRateMultiplier(v float64) *UpstreamResourceAccountUpsert {
	u.Add(upstreamresourceaccount.FieldRateMultiplier, v)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceAccountUpsert) SetSyncedAt(v time.Time) *UpstreamResourceAccountUpsert {
	u.Set(upstreamresourceaccount.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsert) UpdateSyncedAt() *UpstreamResourceAccountUpsert {
	u.SetExcluded(upstreamresourceaccount.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamResourceAccountUpsertOne) UpdateNewValues() *UpstreamResourceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamResourceAccountUpsertOne) Ignore() *UpstreamResourceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamResourceAccountUpsertOne) DoNothing() *UpstreamResourceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamResourceAccountCreate.OnConflict
// documentation for more info.
func (u *UpstreamResourceAccountUpsertOne) Update(set func(*UpstreamResourceAccountUpsert)) *UpstreamResourceAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamResourceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *UpstreamResourceAccountUpsertOne) SetResourceID(v int64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *UpstreamResourceAccountUpsertOne) AddResourceID(v int64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertOne) UpdateResourceID() *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateResourceID()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamResourceAccountUpsertOne) SetPlatform(v string) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertOne) UpdatePlatform() *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdatePlatform()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamResourceAccountUpsertOne) SetAccountID(v int64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamResourceAccountUpsertOne) AddAccountID(v int64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertOne) UpdateAccountID() *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsertOne) SetRateMultiplier(v float64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsertOne) AddRateMultiplier(v float64) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertOne) UpdateRateMultiplier() *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceAccountUpsertOne) SetSyncedAt(v time.Time) *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertOne) UpdateSyncedAt() *UpstreamResourceAccountUpsertOne {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamResourceAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamResourceAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamResourceAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamResourceAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamResourceAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamResourceAccountCreateBulk is the builder for creating many UpstreamResourceAccount entities in bulk.
type UpstreamResourceAccountCreateBulk struct {
	config
	err      error
	builders []*UpstreamResourceAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamResourceAccount entities in the database.
func (_c *UpstreamResourceAccountCreateBulk) Save(ctx context.Context) ([]*UpstreamResourceAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamResourceAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamResourceAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamResourceAccountCreateBulk) SaveX(ctx context.Context) []*UpstreamResourceAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamResourceAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamResourceAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamResourceAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamResourceAccountUpsert) {
//			SetResourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamResourceAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamResourceAccountUpsertBulk {
	_c.conflict = opts
	return &UpstreamResourceAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamResourceAccountCreateBulk) OnConflictColumns(columns ...string) *UpstreamResourceAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamResourceAccountUpsertBulk{
		create: _c,
	}
}

// UpstreamResourceAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamResourceAccount nodes.
type UpstreamResourceAccountUpsertBulk struct {
	create *UpstreamResourceAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamResourceAccountUpsertBulk) UpdateNewValues() *UpstreamResourceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamResourceAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamResourceAccountUpsertBulk) Ignore() *UpstreamResourceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamResourceAccountUpsertBulk) DoNothing() *UpstreamResourceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamResourceAccountCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamResourceAccountUpsertBulk) Update(set func(*UpstreamResourceAccountUpsert)) *UpstreamResourceAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamResourceAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *UpstreamResourceAccountUpsertBulk) SetResourceID(v int64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *UpstreamResourceAccountUpsertBulk) AddResourceID(v int64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertBulk) UpdateResourceID() *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateResourceID()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamResourceAccountUpsertBulk) SetPlatform(v string) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertBulk) UpdatePlatform() *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdatePlatform()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamResourceAccountUpsertBulk) SetAccountID(v int64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamResourceAccountUpsertBulk) AddAccountID(v int64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertBulk) UpdateAccountID() *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsertBulk) SetRateMultiplier(v float64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamResourceAccountUpsertBulk) AddRateMultiplier(v float64) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertBulk) UpdateRateMultiplier() *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceAccountUpsertBulk) SetSyncedAt(v time.Time) *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceAccountUpsertBulk) UpdateSyncedAt() *UpstreamResourceAccountUpsertBulk {
	return u.Update(func(s *UpstreamResourceAccountUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamResourceAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamResourceAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamResourceAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamResourceAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
