// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresource"
)

// UpstreamResourceCreate is the builder for creating a UpstreamResource entity.
type UpstreamResourceCreate struct {
	config
	mutation *UpstreamResourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamResourceCreate) SetCreatedAt(v time.Time) *UpstreamResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableCreatedAt(v *time.Time) *UpstreamResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamResourceCreate) SetUpdatedAt(v time.Time) *UpstreamResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamResourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamResourceCreate) SetDeletedAt(v time.Time) *UpstreamResourceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableDeletedAt(v *time.Time) *UpstreamResourceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUpstreamID sets the "upstream_id" field.
func (_c *UpstreamResourceCreate) SetUpstreamID(v int64) *UpstreamResourceCreate {
	_c.mutation.SetUpstreamID(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *UpstreamResourceCreate) SetResourceType(v string) *UpstreamResourceCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetRemoteID sets the "remote_id" field.
func (_c *UpstreamResourceCreate) SetRemoteID(v string) *UpstreamResourceCreate {
	_c.mutation.SetRemoteID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamResourceCreate) SetName(v string) *UpstreamResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *UpstreamResourceCreate) SetGroupName(v string) *UpstreamResourceCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableGroupName(v *string) *UpstreamResourceCreate {
	if v != nil {
		_c.SetGroupName(*v)
	}
	return _c
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_c *UpstreamResourceCreate) SetKeyEncrypted(v string) *UpstreamResourceCreate {
	_c.mutation.SetKeyEncrypted(v)
	return _c
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (_c *UpstreamResourceCreate) SetModelsSnapshot(v []string) *UpstreamResourceCreate {
	_c.mutation.SetModelsSnapshot(v)
	return _c
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (_c *UpstreamResourceCreate) SetModelsFetchedAt(v time.Time) *UpstreamResourceCreate {
	_c.mutation.SetModelsFetchedAt(v)
	return _c
}

// SetNillableModelsFetchedAt sets the "models_fetched_at" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableModelsFetchedAt(v *time.Time) *UpstreamResourceCreate {
	if v != nil {
		_c.SetModelsFetchedAt(*v)
	}
	return _c
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (_c *UpstreamResourceCreate) SetSyncedAccountID(v int64) *UpstreamResourceCreate {
	_c.mutation.SetSyncedAccountID(v)
	return _c
}

// SetNillableSyncedAccountID sets the "synced_account_id" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableSyncedAccountID(v *int64) *UpstreamResourceCreate {
	if v != nil {
		_c.SetSyncedAccountID(*v)
	}
	return _c
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (_c *UpstreamResourceCreate) SetSyncedRateMultiplier(v float64) *UpstreamResourceCreate {
	_c.mutation.SetSyncedRateMultiplier(v)
	return _c
}

// SetNillableSyncedRateMultiplier sets the "synced_rate_multiplier" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableSyncedRateMultiplier(v *float64) *UpstreamResourceCreate {
	if v != nil {
		_c.SetSyncedRateMultiplier(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *UpstreamResourceCreate) SetSyncedAt(v time.Time) *UpstreamResourceCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableSyncedAt(v *time.Time) *UpstreamResourceCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamResourceCreate) SetEnabled(v bool) *UpstreamResourceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamResourceCreate) SetNillableEnabled(v *bool) *UpstreamResourceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the UpstreamResourceMutation object of the builder.
func (_c *UpstreamResourceCreate) Mutation() *UpstreamResourceMutation {
	return _c.mutation
}

// Save creates the UpstreamResource in the database.
func (_c *UpstreamResourceCreate) Save(ctx context.Context) (*UpstreamResource, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamResourceCreate) SaveX(ctx context.Context) *UpstreamResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamResourceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstreamresource.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamresource.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamresource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstreamresource.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamresource.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamresource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ModelsSnapshot(); !ok {
		v := upstreamresource.DefaultModelsSnapshot
		_c.mutation.SetModelsSnapshot(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreamresource.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamResourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamResource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamResource.updated_at"`)}
	}
	if _, ok := _c.mutation.UpstreamID(); !ok {
		return &ValidationError{Name: "upstream_id", err: errors.New(`ent: missing required field "UpstreamResource.upstream_id"`)}
	}
	if v, ok := _c.mutation.UpstreamID(); ok {
		if err := upstreamresource.UpstreamIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.upstream_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "UpstreamResource.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := upstreamresource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RemoteID(); !ok {
		return &ValidationError{Name: "remote_id", err: errors.New(`ent: missing required field "UpstreamResource.remote_id"`)}
	}
	if v, ok := _c.mutation.RemoteID(); ok {
		if err := upstreamresource.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.remote_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamResource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamresource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := upstreamresource.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyEncrypted(); !ok {
		return &ValidationError{Name: "key_encrypted", err: errors.New(`ent: missing required field "UpstreamResource.key_encrypted"`)}
	}
	if _, ok := _c.mutation.ModelsSnapshot(); !ok {
		return &ValidationError{Name: "models_snapshot", err: errors.New(`ent: missing required field "UpstreamResource.models_snapshot"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamResource.enabled"`)}
	}
	return nil
}

func (_c *UpstreamResourceCreate) sqlSave(ctx context.Context) (*UpstreamResource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamResourceCreate) createSpec() (*UpstreamResource, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamResource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamresource.Table, sqlgraph.NewFieldSpec(upstreamresource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamresource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamresource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamresource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UpstreamID(); ok {
		_spec.SetField(upstreamresource.FieldUpstreamID, field.TypeInt64, value)
		_node.UpstreamID = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(upstreamresource.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.RemoteID(); ok {
		_spec.SetField(upstreamresource.FieldRemoteID, field.TypeString, value)
		_node.RemoteID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamresource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(upstreamresource.FieldGroupName, field.TypeString, value)
		_node.GroupName = &value
	}
	if value, ok := _c.mutation.KeyEncrypted(); ok {
		_spec.SetField(upstreamresource.FieldKeyEncrypted, field.TypeString, value)
		_node.KeyEncrypted = value
	}
	if value, ok := _c.mutation.ModelsSnapshot(); ok {
		_spec.SetField(upstreamresource.FieldModelsSnapshot, field.TypeJSON, value)
		_node.ModelsSnapshot = value
	}
	if value, ok := _c.mutation.ModelsFetchedAt(); ok {
		_spec.SetField(upstreamresource.FieldModelsFetchedAt, field.TypeTime, value)
		_node.ModelsFetchedAt = &value
	}
	if value, ok := _c.mutation.SyncedAccountID(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAccountID, field.TypeInt64, value)
		_node.SyncedAccountID = &value
	}
	if value, ok := _c.mutation.SyncedRateMultiplier(); ok {
		_spec.SetField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64, value)
		_node.SyncedRateMultiplier = &value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreamresource.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamResource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamResourceCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamResourceUpsertOne {
	_c.conflict = opts
	return &UpstreamResourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamResourceCreate) OnConflictColumns(columns ...string) *UpstreamResourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamResourceUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamResourceUpsertOne is the builder for "upsert"-ing
	//  one UpstreamResource node.
	UpstreamResourceUpsertOne struct {
		create *UpstreamResourceCreate
	}

	// UpstreamResourceUpsert is the "OnConflict" setter.
	UpstreamResourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamResourceUpsert) SetUpdatedAt(v time.Time) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateUpdatedAt() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamResourceUpsert) SetDeletedAt(v time.Time) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateDeletedAt() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamResourceUpsert) ClearDeletedAt() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldDeletedAt)
	return u
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamResourceUpsert) SetUpstreamID(v int64) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldUpstreamID, v)
	return u
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateUpstreamID() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldUpstreamID)
	return u
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UpstreamResourceUpsert) AddUpstreamID(v int64) *UpstreamResourceUpsert {
	u.Add(upstreamresource.FieldUpstreamID, v)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *UpstreamResourceUpsert) SetResourceType(v string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateResourceType() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldResourceType)
	return u
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamResourceUpsert) SetRemoteID(v string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldRemoteID, v)
	return u
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateRemoteID() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldRemoteID)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamResourceUpsert) SetName(v string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateName() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldName)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *UpstreamResourceUpsert) SetGroupName(v string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateGroupName() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldGroupName)
	return u
}

// ClearGroupName clears the value of the "group_name" field.
func (u *UpstreamResourceUpsert) ClearGroupName() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldGroupName)
	return u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UpstreamResourceUpsert) SetKeyEncrypted(v string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldKeyEncrypted, v)
	return u
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateKeyEncrypted() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldKeyEncrypted)
	return u
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (u *UpstreamResourceUpsert) SetModelsSnapshot(v []string) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldModelsSnapshot, v)
	return u
}

// UpdateModelsSnapshot sets the "models_snapshot" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateModelsSnapshot() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldModelsSnapshot)
	return u
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (u *UpstreamResourceUpsert) SetModelsFetchedAt(v time.Time) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldModelsFetchedAt, v)
	return u
}

// UpdateModelsFetchedAt sets the "models_fetched_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateModelsFetchedAt() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldModelsFetchedAt)
	return u
}

// ClearModelsFetchedAt clears the value of the "models_fetched_at" field.
func (u *UpstreamResourceUpsert) ClearModelsFetchedAt() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldModelsFetchedAt)
	return u
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (u *UpstreamResourceUpsert) SetSyncedAccountID(v int64) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldSyncedAccountID, v)
	return u
}

// UpdateSyncedAccountID sets the "synced_account_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateSyncedAccountID() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldSyncedAccountID)
	return u
}

// AddSyncedAccountID adds v to the "synced_account_id" field.
func (u *UpstreamResourceUpsert) AddSyncedAccountID(v int64) *UpstreamResourceUpsert {
	u.Add(upstreamresource.FieldSyncedAccountID, v)
	return u
}

// ClearSyncedAccountID clears the value of the "synced_account_id" field.
func (u *UpstreamResourceUpsert) ClearSyncedAccountID() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldSyncedAccountID)
	return u
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsert) SetSyncedRateMultiplier(v float64) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldSyncedRateMultiplier, v)
	return u
}

// UpdateSyncedRateMultiplier sets the "synced_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateSyncedRateMultiplier() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldSyncedRateMultiplier)
	return u
}

// AddSyncedRateMultiplier adds v to the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsert) AddSyncedRateMultiplier(v float64) *UpstreamResourceUpsert {
	u.Add(upstreamresource.FieldSyncedRateMultiplier, v)
	return u
}

// ClearSyncedRateMultiplier clears the value of the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsert) ClearSyncedRateMultiplier() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldSyncedRateMultiplier)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceUpsert) SetSyncedAt(v time.Time) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateSyncedAt() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldSyncedAt)
	return u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *UpstreamResourceUpsert) ClearSyncedAt() *UpstreamResourceUpsert {
	u.SetNull(upstreamresource.FieldSyncedAt)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamResourceUpsert) SetEnabled(v bool) *UpstreamResourceUpsert {
	u.Set(upstreamresource.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamResourceUpsert) UpdateEnabled() *UpstreamResourceUpsert {
	u.SetExcluded(upstreamresource.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamResourceUpsertOne) UpdateNewValues() *UpstreamResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamresource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamResourceUpsertOne) Ignore() *UpstreamResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamResourceUpsertOne) DoNothing() *UpstreamResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamResourceCreate.OnConflict
// documentation for more info.
func (u *UpstreamResourceUpsertOne) Update(set func(*UpstreamResourceUpsert)) *UpstreamResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamResourceUpsertOne) SetUpdatedAt(v time.Time) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateUpdatedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamResourceUpsertOne) SetDeletedAt(v time.Time) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateDeletedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamResourceUpsertOne) ClearDeletedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamResourceUpsertOne) SetUpstreamID(v int64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetUpstreamID(v)
	})
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UpstreamResourceUpsertOne) AddUpstreamID(v int64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateUpstreamID() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateUpstreamID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *UpstreamResourceUpsertOne) SetResourceType(v string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateResourceType() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateResourceType()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamResourceUpsertOne) SetRemoteID(v string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateRemoteID() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateRemoteID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamResourceUpsertOne) SetName(v string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateName() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateName()
	})
}

// SetGroupName sets the "group_name" field.
func (u *UpstreamResourceUpsertOne) SetGroupName(v string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateGroupName() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *UpstreamResourceUpsertOne) ClearGroupName() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearGroupName()
	})
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UpstreamResourceUpsertOne) SetKeyEncrypted(v string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetKeyEncrypted(v)
	})
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateKeyEncrypted() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateKeyEncrypted()
	})
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (u *UpstreamResourceUpsertOne) SetModelsSnapshot(v []string) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetModelsSnapshot(v)
	})
}

// UpdateModelsSnapshot sets the "models_snapshot" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateModelsSnapshot() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateModelsSnapshot()
	})
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (u *UpstreamResourceUpsertOne) SetModelsFetchedAt(v time.Time) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetModelsFetchedAt(v)
	})
}

// UpdateModelsFetchedAt sets the "models_fetched_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateModelsFetchedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateModelsFetchedAt()
	})
}

// ClearModelsFetchedAt clears the value of the "models_fetched_at" field.
func (u *UpstreamResourceUpsertOne) ClearModelsFetchedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearModelsFetchedAt()
	})
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (u *UpstreamResourceUpsertOne) SetSyncedAccountID(v int64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedAccountID(v)
	})
}

// AddSyncedAccountID adds v to the "synced_account_id" field.
func (u *UpstreamResourceUpsertOne) AddSyncedAccountID(v int64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddSyncedAccountID(v)
	})
}

// UpdateSyncedAccountID sets the "synced_account_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateSyncedAccountID() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedAccountID()
	})
}

// ClearSyncedAccountID clears the value of the "synced_account_id" field.
func (u *UpstreamResourceUpsertOne) ClearSyncedAccountID() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedAccountID()
	})
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertOne) SetSyncedRateMultiplier(v float64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedRateMultiplier(v)
	})
}

// AddSyncedRateMultiplier adds v to the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertOne) AddSyncedRateMultiplier(v float64) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddSyncedRateMultiplier(v)
	})
}

// UpdateSyncedRateMultiplier sets the "synced_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateSyncedRateMultiplier() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedRateMultiplier()
	})
}

// ClearSyncedRateMultiplier clears the value of the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertOne) ClearSyncedRateMultiplier() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedRateMultiplier()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceUpsertOne) SetSyncedAt(v time.Time) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateSyncedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedAt()
	})
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *UpstreamResourceUpsertOne) ClearSyncedAt() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamResourceUpsertOne) SetEnabled(v bool) *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamResourceUpsertOne) UpdateEnabled() *UpstreamResourceUpsertOne {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UpstreamResourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamResourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamResourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamResourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamResourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamResourceCreateBulk is the builder for creating many UpstreamResource entities in bulk.
type UpstreamResourceCreateBulk struct {
	config
	err      error
	builders []*UpstreamResourceCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamResource entities in the database.
func (_c *UpstreamResourceCreateBulk) Save(ctx context.Context) ([]*UpstreamResource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamResource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamResourceCreateBulk) SaveX(ctx context.Context) []*UpstreamResource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamResource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamResourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamResourceUpsertBulk {
	_c.conflict = opts
	return &UpstreamResourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamResourceCreateBulk) OnConflictColumns(columns ...string) *UpstreamResourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamResourceUpsertBulk{
		create: _c,
	}
}

// UpstreamResourceUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamResource nodes.
type UpstreamResourceUpsertBulk struct {
	create *UpstreamResourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamResourceUpsertBulk) UpdateNewValues() *UpstreamResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamresource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamResource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamResourceUpsertBulk) Ignore() *UpstreamResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamResourceUpsertBulk) DoNothing() *UpstreamResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamResourceCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamResourceUpsertBulk) Update(set func(*UpstreamResourceUpsert)) *UpstreamResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamResourceUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateUpdatedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamResourceUpsertBulk) SetDeletedAt(v time.Time) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateDeletedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamResourceUpsertBulk) ClearDeletedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpstreamID sets the "upstream_id" field.
func (u *UpstreamResourceUpsertBulk) SetUpstreamID(v int64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetUpstreamID(v)
	})
}

// AddUpstreamID adds v to the "upstream_id" field.
func (u *UpstreamResourceUpsertBulk) AddUpstreamID(v int64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddUpstreamID(v)
	})
}

// UpdateUpstreamID sets the "upstream_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateUpstreamID() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateUpstreamID()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *UpstreamResourceUpsertBulk) SetResourceType(v string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateResourceType() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateResourceType()
	})
}

// SetRemoteID sets the "remote_id" field.
func (u *UpstreamResourceUpsertBulk) SetRemoteID(v string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetRemoteID(v)
	})
}

// UpdateRemoteID sets the "remote_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateRemoteID() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateRemoteID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamResourceUpsertBulk) SetName(v string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateName() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateName()
	})
}

// SetGroupName sets the "group_name" field.
func (u *UpstreamResourceUpsertBulk) SetGroupName(v string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateGroupName() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateGroupName()
	})
}

// ClearGroupName clears the value of the "group_name" field.
func (u *UpstreamResourceUpsertBulk) ClearGroupName() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearGroupName()
	})
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (u *UpstreamResourceUpsertBulk) SetKeyEncrypted(v string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetKeyEncrypted(v)
	})
}

// UpdateKeyEncrypted sets the "key_encrypted" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateKeyEncrypted() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateKeyEncrypted()
	})
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (u *UpstreamResourceUpsertBulk) SetModelsSnapshot(v []string) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetModelsSnapshot(v)
	})
}

// UpdateModelsSnapshot sets the "models_snapshot" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateModelsSnapshot() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateModelsSnapshot()
	})
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (u *UpstreamResourceUpsertBulk) SetModelsFetchedAt(v time.Time) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetModelsFetchedAt(v)
	})
}

// UpdateModelsFetchedAt sets the "models_fetched_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateModelsFetchedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateModelsFetchedAt()
	})
}

// ClearModelsFetchedAt clears the value of the "models_fetched_at" field.
func (u *UpstreamResourceUpsertBulk) ClearModelsFetchedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearModelsFetchedAt()
	})
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (u *UpstreamResourceUpsertBulk) SetSyncedAccountID(v int64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedAccountID(v)
	})
}

// AddSyncedAccountID adds v to the "synced_account_id" field.
func (u *UpstreamResourceUpsertBulk) AddSyncedAccountID(v int64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddSyncedAccountID(v)
	})
}

// UpdateSyncedAccountID sets the "synced_account_id" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateSyncedAccountID() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedAccountID()
	})
}

// ClearSyncedAccountID clears the value of the "synced_account_id" field.
func (u *UpstreamResourceUpsertBulk) ClearSyncedAccountID() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedAccountID()
	})
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertBulk) SetSyncedRateMultiplier(v float64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedRateMultiplier(v)
	})
}

// AddSyncedRateMultiplier adds v to the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertBulk) AddSyncedRateMultiplier(v float64) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.AddSyncedRateMultiplier(v)
	})
}

// UpdateSyncedRateMultiplier sets the "synced_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateSyncedRateMultiplier() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedRateMultiplier()
	})
}

// ClearSyncedRateMultiplier clears the value of the "synced_rate_multiplier" field.
func (u *UpstreamResourceUpsertBulk) ClearSyncedRateMultiplier() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedRateMultiplier()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamResourceUpsertBulk) SetSyncedAt(v time.Time) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateSyncedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateSyncedAt()
	})
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *UpstreamResourceUpsertBulk) ClearSyncedAt() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.ClearSyncedAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamResourceUpsertBulk) SetEnabled(v bool) *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamResourceUpsertBulk) UpdateEnabled() *UpstreamResourceUpsertBulk {
	return u.Update(func(s *UpstreamResourceUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UpstreamResourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamResourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamResourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamResourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
