// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresourceaccount"
)

// UpstreamResourceAccountUpdate is the builder for updating UpstreamResourceAccount entities.
type UpstreamResourceAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamResourceAccountMutation
}

// Where appends a list predicates to the UpstreamResourceAccountUpdate builder.
func (_u *UpstreamResourceAccountUpdate) Where(ps ...predicate.UpstreamResourceAccount) *UpstreamResourceAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UpstreamResourceAccountUpdate) SetResourceID(v int64) *UpstreamResourceAccountUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdate) SetNillableResourceID(v *int64) *UpstreamResourceAccountUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UpstreamResourceAccountUpdate) AddResourceID(v int64) *UpstreamResourceAccountUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamResourceAccountUpdate) SetPlatform(v string) *UpstreamResourceAccountUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdate) SetNillablePlatform(v *string) *UpstreamResourceAccountUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamResourceAccountUpdate) SetAccountID(v int64) *UpstreamResourceAccountUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdate) SetNillableAccountID(v *int64) *UpstreamResourceAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamResourceAccountUpdate) AddAccountID(v int64) *UpstreamResourceAccountUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *UpstreamResourceAccountUpdate) SetRateMultiplier(v float64) *UpstreamResourceAccountUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdate) SetNillableRateMultiplier(v *float64) *UpstreamResourceAccountUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *UpstreamResourceAccountUpdate) AddRateMultiplier(v float64) *UpstreamResourceAccountUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UpstreamResourceAccountUpdate) SetSyncedAt(v time.Time) *UpstreamResourceAccountUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdate) SetNillableSyncedAt(v *time.Time) *UpstreamResourceAccountUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamResourceAccountMutation object of the builder.
func (_u *UpstreamResourceAccountUpdate) Mutation() *UpstreamResourceAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamResourceAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamResourceAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamResourceAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamResourceAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamResourceAccountUpdate) check() error {
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := upstreamresourceaccount.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamresourceaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := upstreamresourceaccount.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.account_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamResourceAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamresourceaccount.Table, upstreamresourceaccount.Columns, sqlgraph.NewFieldSpec(upstreamresourceaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(upstreamresourceaccount.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamresourceaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreamresourceaccount.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(upstreamresourceaccount.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(upstreamresourceaccount.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresourceaccount.FieldSyncedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamresourceaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamResourceAccountUpdateOne is the builder for updating a single UpstreamResourceAccount entity.
type UpstreamResourceAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamResourceAccountMutation
}

// SetResourceID sets the "resource_id" field.
func (_u *UpstreamResourceAccountUpdateOne) SetResourceID(v int64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdateOne) SetNillableResourceID(v *int64) *UpstreamResourceAccountUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *UpstreamResourceAccountUpdateOne) AddResourceID(v int64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UpstreamResourceAccountUpdateOne) SetPlatform(v string) *UpstreamResourceAccountUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdateOne) SetNillablePlatform(v *string) *UpstreamResourceAccountUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamResourceAccountUpdateOne) SetAccountID(v int64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdateOne) SetNillableAccountID(v *int64) *UpstreamResourceAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamResourceAccountUpdateOne) AddAccountID(v int64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *UpstreamResourceAccountUpdateOne) SetRateMultiplier(v float64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdateOne) SetNillableRateMultiplier(v *float64) *UpstreamResourceAccountUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *UpstreamResourceAccountUpdateOne) AddRateMultiplier(v float64) *UpstreamResourceAccountUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UpstreamResourceAccountUpdateOne) SetSyncedAt(v time.Time) *UpstreamResourceAccountUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UpstreamResourceAccountUpdateOne) SetNillableSyncedAt(v *time.Time) *UpstreamResourceAccountUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamResourceAccountMutation object of the builder.
func (_u *UpstreamResourceAccountUpdateOne) Mutation() *UpstreamResourceAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamResourceAccountUpdate builder.
func (_u *UpstreamResourceAccountUpdateOne) Where(ps ...predicate.UpstreamResourceAccount) *UpstreamResourceAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamResourceAccountUpdateOne) Select(field string, fields ...string) *UpstreamResourceAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamResourceAccount entity.
func (_u *UpstreamResourceAccountUpdateOne) Save(ctx context.Context) (*UpstreamResourceAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamResourceAccountUpdateOne) SaveX(ctx context.Context) *UpstreamResourceAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamResourceAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamResourceAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamResourceAccountUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := upstreamresourceaccount.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := upstreamresourceaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountID(); ok {
		if err := upstreamresourceaccount.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResourceAccount.account_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamResourceAccountUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamResourceAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamresourceaccount.Table, upstreamresourceaccount.Columns, sqlgraph.NewFieldSpec(upstreamresourceaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamResourceAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamresourceaccount.FieldID)
		for _, f := range fields {
			if !upstreamresourceaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamresourceaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(upstreamresourceaccount.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(upstreamresourceaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreamresourceaccount.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreamresourceaccount.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(upstreamresourceaccount.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(upstreamresourceaccount.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresourceaccount.FieldSyncedAt, field.TypeTime, value)
	}
	_node = &UpstreamResourceAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamresourceaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
