// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresource"
)

// UpstreamResource is the model entity for the UpstreamResource schema.
type UpstreamResource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UpstreamID holds the value of the "upstream_id" field.
	UpstreamID int64 `json:"upstream_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// RemoteID holds the value of the "remote_id" field.
	RemoteID string `json:"remote_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName *string `json:"group_name,omitempty"`
	// KeyEncrypted holds the value of the "key_encrypted" field.
	KeyEncrypted string `json:"-"`
	// ModelsSnapshot holds the value of the "models_snapshot" field.
	ModelsSnapshot []string `json:"models_snapshot,omitempty"`
	// ModelsFetchedAt holds the value of the "models_fetched_at" field.
	ModelsFetchedAt *time.Time `json:"models_fetched_at,omitempty"`
	// SyncedAccountID holds the value of the "synced_account_id" field.
	SyncedAccountID *int64 `json:"synced_account_id,omitempty"`
	// SyncedRateMultiplier holds the value of the "synced_rate_multiplier" field.
	SyncedRateMultiplier *float64 `json:"synced_rate_multiplier,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt *time.Time `json:"synced_at,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamResource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamresource.FieldModelsSnapshot:
			values[i] = new([]byte)
		case upstreamresource.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreamresource.FieldSyncedRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case upstreamresource.FieldID, upstreamresource.FieldUpstreamID, upstreamresource.FieldSyncedAccountID:
			values[i] = new(sql.NullInt64)
		case upstreamresource.FieldResourceType, upstreamresource.FieldRemoteID, upstreamresource.FieldName, upstreamresource.FieldGroupName, upstreamresource.FieldKeyEncrypted:
			values[i] = new(sql.NullString)
		case upstreamresource.FieldCreatedAt, upstreamresource.FieldUpdatedAt, upstreamresource.FieldDeletedAt, upstreamresource.FieldModelsFetchedAt, upstreamresource.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamResource fields.
func (_m *UpstreamResource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamresource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamresource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamresource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamresource.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case upstreamresource.FieldUpstreamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_id", values[i])
			} else if value.Valid {
				_m.UpstreamID = value.Int64
			}
		case upstreamresource.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case upstreamresource.FieldRemoteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_id", values[i])
			} else if value.Valid {
				_m.RemoteID = value.String
			}
		case upstreamresource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamresource.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = new(string)
				*_m.GroupName = value.String
			}
		case upstreamresource.FieldKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_encrypted", values[i])
			} else if value.Valid {
				_m.KeyEncrypted = value.String
			}
		case upstreamresource.FieldModelsSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field models_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelsSnapshot); err != nil {
					return fmt.Errorf("unmarshal field models_snapshot: %w", err)
				}
			}
		case upstreamresource.FieldModelsFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field models_fetched_at", values[i])
			} else if value.Valid {
				_m.ModelsFetchedAt = new(time.Time)
				*_m.ModelsFetchedAt = value.Time
			}
		case upstreamresource.FieldSyncedAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field synced_account_id", values[i])
			} else if value.Valid {
				_m.SyncedAccountID = new(int64)
				*_m.SyncedAccountID = value.Int64
			}
		case upstreamresource.FieldSyncedRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field synced_rate_multiplier", values[i])
			} else if value.Valid {
				_m.SyncedRateMultiplier = new(float64)
				*_m.SyncedRateMultiplier = value.Float64
			}
		case upstreamresource.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = new(time.Time)
				*_m.SyncedAt = value.Time
			}
		case upstreamresource.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamResource.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamResource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamResource.
// Note that you need to call UpstreamResource.Unwrap() before calling this method if this UpstreamResource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamResource) Update() *UpstreamResourceUpdateOne {
	return NewUpstreamResourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamResource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamResource) Unwrap() *UpstreamResource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamResource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamResource) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamResource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamID))
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("remote_id=")
	builder.WriteString(_m.RemoteID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.GroupName; v != nil {
		builder.WriteString("group_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("key_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("models_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelsSnapshot))
	builder.WriteString(", ")
	if v := _m.ModelsFetchedAt; v != nil {
		builder.WriteString("models_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SyncedAccountID; v != nil {
		builder.WriteString("synced_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SyncedRateMultiplier; v != nil {
		builder.WriteString("synced_rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SyncedAt; v != nil {
		builder.WriteString("synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamResources is a parsable slice of UpstreamResource.
type UpstreamResources []*UpstreamResource
