// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// Upstream is the model entity for the Upstream schema.
type Upstream struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SortCode holds the value of the "sort_code" field.
	SortCode int `json:"sort_code,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// TokenEncrypted holds the value of the "token_encrypted" field.
	TokenEncrypted string `json:"-"`
	// RefreshTokenEncrypted holds the value of the "refresh_token_encrypted" field.
	RefreshTokenEncrypted *string `json:"-"`
	// PasswordEncrypted holds the value of the "password_encrypted" field.
	PasswordEncrypted string `json:"-"`
	// TokenExpiresAt holds the value of the "token_expires_at" field.
	TokenExpiresAt *time.Time `json:"token_expires_at,omitempty"`
	// LoginIdentifier holds the value of the "login_identifier" field.
	LoginIdentifier *string `json:"login_identifier,omitempty"`
	// RemoteUserID holds the value of the "remote_user_id" field.
	RemoteUserID *string `json:"remote_user_id,omitempty"`
	// BalanceSnapshot holds the value of the "balance_snapshot" field.
	BalanceSnapshot map[string]interface{} `json:"balance_snapshot,omitempty"`
	// GroupSnapshot holds the value of the "group_snapshot" field.
	GroupSnapshot map[string]interface{} `json:"group_snapshot,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy    int64 `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Upstream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstream.FieldBalanceSnapshot, upstream.FieldGroupSnapshot:
			values[i] = new([]byte)
		case upstream.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstream.FieldID, upstream.FieldSortCode, upstream.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case upstream.FieldName, upstream.FieldKind, upstream.FieldBaseURL, upstream.FieldTokenEncrypted, upstream.FieldRefreshTokenEncrypted, upstream.FieldPasswordEncrypted, upstream.FieldLoginIdentifier, upstream.FieldRemoteUserID, upstream.FieldNotes, upstream.FieldLastError:
			values[i] = new(sql.NullString)
		case upstream.FieldCreatedAt, upstream.FieldUpdatedAt, upstream.FieldDeletedAt, upstream.FieldTokenExpiresAt, upstream.FieldLastCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Upstream fields.
func (_m *Upstream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstream.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstream.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstream.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstream.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case upstream.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstream.FieldSortCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_code", values[i])
			} else if value.Valid {
				_m.SortCode = int(value.Int64)
			}
		case upstream.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case upstream.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstream.FieldTokenEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_encrypted", values[i])
			} else if value.Valid {
				_m.TokenEncrypted = value.String
			}
		case upstream.FieldRefreshTokenEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_encrypted", values[i])
			} else if value.Valid {
				_m.RefreshTokenEncrypted = new(string)
				*_m.RefreshTokenEncrypted = value.String
			}
		case upstream.FieldPasswordEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_encrypted", values[i])
			} else if value.Valid {
				_m.PasswordEncrypted = value.String
			}
		case upstream.FieldTokenExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_expires_at", values[i])
			} else if value.Valid {
				_m.TokenExpiresAt = new(time.Time)
				*_m.TokenExpiresAt = value.Time
			}
		case upstream.FieldLoginIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login_identifier", values[i])
			} else if value.Valid {
				_m.LoginIdentifier = new(string)
				*_m.LoginIdentifier = value.String
			}
		case upstream.FieldRemoteUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_user_id", values[i])
			} else if value.Valid {
				_m.RemoteUserID = new(string)
				*_m.RemoteUserID = value.String
			}
		case upstream.FieldBalanceSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field balance_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BalanceSnapshot); err != nil {
					return fmt.Errorf("unmarshal field balance_snapshot: %w", err)
				}
			}
		case upstream.FieldGroupSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field group_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GroupSnapshot); err != nil {
					return fmt.Errorf("unmarshal field group_snapshot: %w", err)
				}
			}
		case upstream.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case upstream.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstream.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case upstream.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case upstream.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Upstream.
// This includes values selected through modifiers, order, etc.
func (_m *Upstream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Upstream.
// Note that you need to call Upstream.Unwrap() before calling this method if this Upstream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Upstream) Update() *UpstreamUpdateOne {
	return NewUpstreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Upstream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Upstream) Unwrap() *Upstream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Upstream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Upstream) String() string {
	var builder strings.Builder
	builder.WriteString("Upstream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("sort_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortCode))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("token_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("password_encrypted=<sensitive>")
	builder.WriteString(", ")
	if v := _m.TokenExpiresAt; v != nil {
		builder.WriteString("token_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LoginIdentifier; v != nil {
		builder.WriteString("login_identifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RemoteUserID; v != nil {
		builder.WriteString("remote_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("balance_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceSnapshot))
	builder.WriteString(", ")
	builder.WriteString("group_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupSnapshot))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// Upstreams is a parsable slice of Upstream.
type Upstreams []*Upstream
