// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// UpstreamCreate is the builder for creating a Upstream entity.
type UpstreamCreate struct {
	config
	mutation *UpstreamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamCreate) SetCreatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableCreatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamCreate) SetUpdatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamCreate) SetDeletedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableDeletedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamCreate) SetName(v string) *UpstreamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortCode sets the "sort_code" field.
func (_c *UpstreamCreate) SetSortCode(v int) *UpstreamCreate {
	_c.mutation.SetSortCode(v)
	return _c
}

// SetNillableSortCode sets the "sort_code" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableSortCode(v *int) *UpstreamCreate {
	if v != nil {
		_c.SetSortCode(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *UpstreamCreate) SetKind(v string) *UpstreamCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamCreate) SetBaseURL(v string) *UpstreamCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_c *UpstreamCreate) SetTokenEncrypted(v string) *UpstreamCreate {
	_c.mutation.SetTokenEncrypted(v)
	return _c
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_c *UpstreamCreate) SetRefreshTokenEncrypted(v string) *UpstreamCreate {
	_c.mutation.SetRefreshTokenEncrypted(v)
	return _c
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableRefreshTokenEncrypted(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetRefreshTokenEncrypted(*v)
	}
	return _c
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_c *UpstreamCreate) SetPasswordEncrypted(v string) *UpstreamCreate {
	_c.mutation.SetPasswordEncrypted(v)
	return _c
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillablePasswordEncrypted(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetPasswordEncrypted(*v)
	}
	return _c
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_c *UpstreamCreate) SetTokenExpiresAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetTokenExpiresAt(v)
	return _c
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableTokenExpiresAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetTokenExpiresAt(*v)
	}
	return _c
}

// SetLoginIdentifier sets the "login_identifier" field.
func (_c *UpstreamCreate) SetLoginIdentifier(v string) *UpstreamCreate {
	_c.mutation.SetLoginIdentifier(v)
	return _c
}

// SetNillableLoginIdentifier sets the "login_identifier" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLoginIdentifier(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetLoginIdentifier(*v)
	}
	return _c
}

// SetRemoteUserID sets the "remote_user_id" field.
func (_c *UpstreamCreate) SetRemoteUserID(v string) *UpstreamCreate {
	_c.mutation.SetRemoteUserID(v)
	return _c
}

// SetNillableRemoteUserID sets the "remote_user_id" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableRemoteUserID(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetRemoteUserID(*v)
	}
	return _c
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (_c *UpstreamCreate) SetBalanceSnapshot(v map[string]interface{}) *UpstreamCreate {
	_c.mutation.SetBalanceSnapshot(v)
	return _c
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (_c *UpstreamCreate) SetGroupSnapshot(v map[string]interface{}) *UpstreamCreate {
	_c.mutation.SetGroupSnapshot(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UpstreamCreate) SetNotes(v string) *UpstreamCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableNotes(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamCreate) SetEnabled(v bool) *UpstreamCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableEnabled(v *bool) *UpstreamCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *UpstreamCreate) SetLastCheckedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLastCheckedAt(v *time.Time) *UpstreamCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *UpstreamCreate) SetLastError(v string) *UpstreamCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableLastError(v *string) *UpstreamCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UpstreamCreate) SetCreatedBy(v int64) *UpstreamCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// Mutation returns the UpstreamMutation object of the builder.
func (_c *UpstreamCreate) Mutation() *UpstreamMutation {
	return _c.mutation
}

// Save creates the Upstream in the database.
func (_c *UpstreamCreate) Save(ctx context.Context) (*Upstream, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamCreate) SaveX(ctx context.Context) *Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstream.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstream.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortCode(); !ok {
		v := upstream.DefaultSortCode
		_c.mutation.SetSortCode(v)
	}
	if _, ok := _c.mutation.BalanceSnapshot(); !ok {
		v := upstream.DefaultBalanceSnapshot
		_c.mutation.SetBalanceSnapshot(v)
	}
	if _, ok := _c.mutation.GroupSnapshot(); !ok {
		v := upstream.DefaultGroupSnapshot
		_c.mutation.SetGroupSnapshot(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstream.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Upstream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Upstream.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Upstream.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortCode(); !ok {
		return &ValidationError{Name: "sort_code", err: errors.New(`ent: missing required field "Upstream.sort_code"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Upstream.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := upstream.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Upstream.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "Upstream.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenEncrypted(); !ok {
		return &ValidationError{Name: "token_encrypted", err: errors.New(`ent: missing required field "Upstream.token_encrypted"`)}
	}
	if v, ok := _c.mutation.LoginIdentifier(); ok {
		if err := upstream.LoginIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "login_identifier", err: fmt.Errorf(`ent: validator failed for field "Upstream.login_identifier": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RemoteUserID(); ok {
		if err := upstream.RemoteUserIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_user_id", err: fmt.Errorf(`ent: validator failed for field "Upstream.remote_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceSnapshot(); !ok {
		return &ValidationError{Name: "balance_snapshot", err: errors.New(`ent: missing required field "Upstream.balance_snapshot"`)}
	}
	if _, ok := _c.mutation.GroupSnapshot(); !ok {
		return &ValidationError{Name: "group_snapshot", err: errors.New(`ent: missing required field "Upstream.group_snapshot"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Upstream.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Upstream.created_by"`)}
	}
	return nil
}

func (_c *UpstreamCreate) sqlSave(ctx context.Context) (*Upstream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamCreate) createSpec() (*Upstream, *sqlgraph.CreateSpec) {
	var (
		_node = &Upstream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstream.Table, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortCode(); ok {
		_spec.SetField(upstream.FieldSortCode, field.TypeInt, value)
		_node.SortCode = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(upstream.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.TokenEncrypted(); ok {
		_spec.SetField(upstream.FieldTokenEncrypted, field.TypeString, value)
		_node.TokenEncrypted = value
	}
	if value, ok := _c.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstream.FieldRefreshTokenEncrypted, field.TypeString, value)
		_node.RefreshTokenEncrypted = &value
	}
	if value, ok := _c.mutation.PasswordEncrypted(); ok {
		_spec.SetField(upstream.FieldPasswordEncrypted, field.TypeString, value)
		_node.PasswordEncrypted = value
	}
	if value, ok := _c.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstream.FieldTokenExpiresAt, field.TypeTime, value)
		_node.TokenExpiresAt = &value
	}
	if value, ok := _c.mutation.LoginIdentifier(); ok {
		_spec.SetField(upstream.FieldLoginIdentifier, field.TypeString, value)
		_node.LoginIdentifier = &value
	}
	if value, ok := _c.mutation.RemoteUserID(); ok {
		_spec.SetField(upstream.FieldRemoteUserID, field.TypeString, value)
		_node.RemoteUserID = &value
	}
	if value, ok := _c.mutation.BalanceSnapshot(); ok {
		_spec.SetField(upstream.FieldBalanceSnapshot, field.TypeJSON, value)
		_node.BalanceSnapshot = value
	}
	if value, ok := _c.mutation.GroupSnapshot(); ok {
		_spec.SetField(upstream.FieldGroupSnapshot, field.TypeJSON, value)
		_node.GroupSnapshot = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(upstream.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstream.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(upstream.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(upstream.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(upstream.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertOne {
	_c.conflict = opts
	return &UpstreamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreate) OnConflictColumns(columns ...string) *UpstreamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamUpsertOne is the builder for "upsert"-ing
	//  one Upstream node.
	UpstreamUpsertOne struct {
		create *UpstreamCreate
	}

	// UpstreamUpsert is the "OnConflict" setter.
	UpstreamUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsert) SetUpdatedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateUpdatedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsert) SetDeletedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateDeletedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsert) ClearDeletedAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamUpsert) SetName(v string) *UpstreamUpsert {
	u.Set(upstream.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateName() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldName)
	return u
}

// SetSortCode sets the "sort_code" field.
func (u *UpstreamUpsert) SetSortCode(v int) *UpstreamUpsert {
	u.Set(upstream.FieldSortCode, v)
	return u
}

// UpdateSortCode sets the "sort_code" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateSortCode() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldSortCode)
	return u
}

// AddSortCode adds v to the "sort_code" field.
func (u *UpstreamUpsert) AddSortCode(v int) *UpstreamUpsert {
	u.Add(upstream.FieldSortCode, v)
	return u
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsert) SetKind(v string) *UpstreamUpsert {
	u.Set(upstream.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateKind() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldKind)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsert) SetBaseURL(v string) *UpstreamUpsert {
	u.Set(upstream.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateBaseURL() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldBaseURL)
	return u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *UpstreamUpsert) SetTokenEncrypted(v string) *UpstreamUpsert {
	u.Set(upstream.FieldTokenEncrypted, v)
	return u
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateTokenEncrypted() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldTokenEncrypted)
	return u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamUpsert) SetRefreshTokenEncrypted(v string) *UpstreamUpsert {
	u.Set(upstream.FieldRefreshTokenEncrypted, v)
	return u
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateRefreshTokenEncrypted() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldRefreshTokenEncrypted)
	return u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamUpsert) ClearRefreshTokenEncrypted() *UpstreamUpsert {
	u.SetNull(upstream.FieldRefreshTokenEncrypted)
	return u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *UpstreamUpsert) SetPasswordEncrypted(v string) *UpstreamUpsert {
	u.Set(upstream.FieldPasswordEncrypted, v)
	return u
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdatePasswordEncrypted() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldPasswordEncrypted)
	return u
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (u *UpstreamUpsert) ClearPasswordEncrypted() *UpstreamUpsert {
	u.SetNull(upstream.FieldPasswordEncrypted)
	return u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamUpsert) SetTokenExpiresAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldTokenExpiresAt, v)
	return u
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateTokenExpiresAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldTokenExpiresAt)
	return u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamUpsert) ClearTokenExpiresAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldTokenExpiresAt)
	return u
}

// SetLoginIdentifier sets the "login_identifier" field.
func (u *UpstreamUpsert) SetLoginIdentifier(v string) *UpstreamUpsert {
	u.Set(upstream.FieldLoginIdentifier, v)
	return u
}

// UpdateLoginIdentifier sets the "login_identifier" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLoginIdentifier() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLoginIdentifier)
	return u
}

// ClearLoginIdentifier clears the value of the "login_identifier" field.
func (u *UpstreamUpsert) ClearLoginIdentifier() *UpstreamUpsert {
	u.SetNull(upstream.FieldLoginIdentifier)
	return u
}

// SetRemoteUserID sets the "remote_user_id" field.
func (u *UpstreamUpsert) SetRemoteUserID(v string) *UpstreamUpsert {
	u.Set(upstream.FieldRemoteUserID, v)
	return u
}

// UpdateRemoteUserID sets the "remote_user_id" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateRemoteUserID() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldRemoteUserID)
	return u
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (u *UpstreamUpsert) ClearRemoteUserID() *UpstreamUpsert {
	u.SetNull(upstream.FieldRemoteUserID)
	return u
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (u *UpstreamUpsert) SetBalanceSnapshot(v map[string]interface{}) *UpstreamUpsert {
	u.Set(upstream.FieldBalanceSnapshot, v)
	return u
}

// UpdateBalanceSnapshot sets the "balance_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateBalanceSnapshot() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldBalanceSnapshot)
	return u
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (u *UpstreamUpsert) SetGroupSnapshot(v map[string]interface{}) *UpstreamUpsert {
	u.Set(upstream.FieldGroupSnapshot, v)
	return u
}

// UpdateGroupSnapshot sets the "group_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateGroupSnapshot() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldGroupSnapshot)
	return u
}

// SetNotes sets the "notes" field.
func (u *UpstreamUpsert) SetNotes(v string) *UpstreamUpsert {
	u.Set(upstream.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateNotes() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UpstreamUpsert) ClearNotes() *UpstreamUpsert {
	u.SetNull(upstream.FieldNotes)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamUpsert) SetEnabled(v bool) *UpstreamUpsert {
	u.Set(upstream.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateEnabled() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldEnabled)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamUpsert) SetLastCheckedAt(v time.Time) *UpstreamUpsert {
	u.Set(upstream.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLastCheckedAt() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamUpsert) ClearLastCheckedAt() *UpstreamUpsert {
	u.SetNull(upstream.FieldLastCheckedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *UpstreamUpsert) SetLastError(v string) *UpstreamUpsert {
	u.Set(upstream.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateLastError() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamUpsert) ClearLastError() *UpstreamUpsert {
	u.SetNull(upstream.FieldLastError)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamUpsert) SetCreatedBy(v int64) *UpstreamUpsert {
	u.Set(upstream.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamUpsert) UpdateCreatedBy() *UpstreamUpsert {
	u.SetExcluded(upstream.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamUpsert) AddCreatedBy(v int64) *UpstreamUpsert {
	u.Add(upstream.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertOne) UpdateNewValues() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstream.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamUpsertOne) Ignore() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertOne) DoNothing() *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreate.OnConflict
// documentation for more info.
func (u *UpstreamUpsertOne) Update(set func(*UpstreamUpsert)) *UpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertOne) SetUpdatedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateUpdatedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertOne) SetDeletedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertOne) ClearDeletedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertOne) SetName(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateName() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetSortCode sets the "sort_code" field.
func (u *UpstreamUpsertOne) SetSortCode(v int) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetSortCode(v)
	})
}

// AddSortCode adds v to the "sort_code" field.
func (u *UpstreamUpsertOne) AddSortCode(v int) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddSortCode(v)
	})
}

// UpdateSortCode sets the "sort_code" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateSortCode() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateSortCode()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsertOne) SetKind(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateKind() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateKind()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertOne) SetBaseURL(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateBaseURL() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *UpstreamUpsertOne) SetTokenEncrypted(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetTokenEncrypted(v)
	})
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateTokenEncrypted() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamUpsertOne) SetRefreshTokenEncrypted(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateRefreshTokenEncrypted() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamUpsertOne) ClearRefreshTokenEncrypted() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *UpstreamUpsertOne) SetPasswordEncrypted(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdatePasswordEncrypted() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (u *UpstreamUpsertOne) ClearPasswordEncrypted() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearPasswordEncrypted()
	})
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamUpsertOne) SetTokenExpiresAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetTokenExpiresAt(v)
	})
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateTokenExpiresAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateTokenExpiresAt()
	})
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamUpsertOne) ClearTokenExpiresAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearTokenExpiresAt()
	})
}

// SetLoginIdentifier sets the "login_identifier" field.
func (u *UpstreamUpsertOne) SetLoginIdentifier(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLoginIdentifier(v)
	})
}

// UpdateLoginIdentifier sets the "login_identifier" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLoginIdentifier() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLoginIdentifier()
	})
}

// ClearLoginIdentifier clears the value of the "login_identifier" field.
func (u *UpstreamUpsertOne) ClearLoginIdentifier() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLoginIdentifier()
	})
}

// SetRemoteUserID sets the "remote_user_id" field.
func (u *UpstreamUpsertOne) SetRemoteUserID(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRemoteUserID(v)
	})
}

// UpdateRemoteUserID sets the "remote_user_id" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateRemoteUserID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRemoteUserID()
	})
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (u *UpstreamUpsertOne) ClearRemoteUserID() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRemoteUserID()
	})
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (u *UpstreamUpsertOne) SetBalanceSnapshot(v map[string]interface{}) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBalanceSnapshot(v)
	})
}

// UpdateBalanceSnapshot sets the "balance_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateBalanceSnapshot() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBalanceSnapshot()
	})
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (u *UpstreamUpsertOne) SetGroupSnapshot(v map[string]interface{}) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetGroupSnapshot(v)
	})
}

// UpdateGroupSnapshot sets the "group_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateGroupSnapshot() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateGroupSnapshot()
	})
}

// SetNotes sets the "notes" field.
func (u *UpstreamUpsertOne) SetNotes(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateNotes() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UpstreamUpsertOne) ClearNotes() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearNotes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamUpsertOne) SetEnabled(v bool) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateEnabled() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateEnabled()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamUpsertOne) SetLastCheckedAt(v time.Time) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLastCheckedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamUpsertOne) ClearLastCheckedAt() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamUpsertOne) SetLastError(v string) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateLastError() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamUpsertOne) ClearLastError() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamUpsertOne) SetCreatedBy(v int64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamUpsertOne) AddCreatedBy(v int64) *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamUpsertOne) UpdateCreatedBy() *UpstreamUpsertOne {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamCreateBulk is the builder for creating many Upstream entities in bulk.
type UpstreamCreateBulk struct {
	config
	err      error
	builders []*UpstreamCreate
	conflict []sql.ConflictOption
}

// Save creates the Upstream entities in the database.
func (_c *UpstreamCreateBulk) Save(ctx context.Context) ([]*Upstream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Upstream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamCreateBulk) SaveX(ctx context.Context) []*Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Upstream.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamUpsertBulk {
	_c.conflict = opts
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamCreateBulk) OnConflictColumns(columns ...string) *UpstreamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUpsertBulk{
		create: _c,
	}
}

// UpstreamUpsertBulk is the builder for "upsert"-ing
// a bulk of Upstream nodes.
type UpstreamUpsertBulk struct {
	create *UpstreamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) UpdateNewValues() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstream.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Upstream.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamUpsertBulk) Ignore() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUpsertBulk) DoNothing() *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamUpsertBulk) Update(set func(*UpstreamUpsert)) *UpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateUpdatedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamUpsertBulk) SetDeletedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamUpsertBulk) ClearDeletedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamUpsertBulk) SetName(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateName() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateName()
	})
}

// SetSortCode sets the "sort_code" field.
func (u *UpstreamUpsertBulk) SetSortCode(v int) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetSortCode(v)
	})
}

// AddSortCode adds v to the "sort_code" field.
func (u *UpstreamUpsertBulk) AddSortCode(v int) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddSortCode(v)
	})
}

// UpdateSortCode sets the "sort_code" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateSortCode() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateSortCode()
	})
}

// SetKind sets the "kind" field.
func (u *UpstreamUpsertBulk) SetKind(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateKind() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateKind()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamUpsertBulk) SetBaseURL(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateBaseURL() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (u *UpstreamUpsertBulk) SetTokenEncrypted(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetTokenEncrypted(v)
	})
}

// UpdateTokenEncrypted sets the "token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateTokenEncrypted() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamUpsertBulk) SetRefreshTokenEncrypted(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateRefreshTokenEncrypted() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamUpsertBulk) ClearRefreshTokenEncrypted() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *UpstreamUpsertBulk) SetPasswordEncrypted(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdatePasswordEncrypted() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (u *UpstreamUpsertBulk) ClearPasswordEncrypted() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearPasswordEncrypted()
	})
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamUpsertBulk) SetTokenExpiresAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetTokenExpiresAt(v)
	})
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateTokenExpiresAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateTokenExpiresAt()
	})
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamUpsertBulk) ClearTokenExpiresAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearTokenExpiresAt()
	})
}

// SetLoginIdentifier sets the "login_identifier" field.
func (u *UpstreamUpsertBulk) SetLoginIdentifier(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLoginIdentifier(v)
	})
}

// UpdateLoginIdentifier sets the "login_identifier" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLoginIdentifier() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLoginIdentifier()
	})
}

// ClearLoginIdentifier clears the value of the "login_identifier" field.
func (u *UpstreamUpsertBulk) ClearLoginIdentifier() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLoginIdentifier()
	})
}

// SetRemoteUserID sets the "remote_user_id" field.
func (u *UpstreamUpsertBulk) SetRemoteUserID(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetRemoteUserID(v)
	})
}

// UpdateRemoteUserID sets the "remote_user_id" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateRemoteUserID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateRemoteUserID()
	})
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (u *UpstreamUpsertBulk) ClearRemoteUserID() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearRemoteUserID()
	})
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (u *UpstreamUpsertBulk) SetBalanceSnapshot(v map[string]interface{}) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetBalanceSnapshot(v)
	})
}

// UpdateBalanceSnapshot sets the "balance_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateBalanceSnapshot() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateBalanceSnapshot()
	})
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (u *UpstreamUpsertBulk) SetGroupSnapshot(v map[string]interface{}) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetGroupSnapshot(v)
	})
}

// UpdateGroupSnapshot sets the "group_snapshot" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateGroupSnapshot() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateGroupSnapshot()
	})
}

// SetNotes sets the "notes" field.
func (u *UpstreamUpsertBulk) SetNotes(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateNotes() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UpstreamUpsertBulk) ClearNotes() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearNotes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamUpsertBulk) SetEnabled(v bool) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateEnabled() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateEnabled()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamUpsertBulk) SetLastCheckedAt(v time.Time) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLastCheckedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamUpsertBulk) ClearLastCheckedAt() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamUpsertBulk) SetLastError(v string) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateLastError() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamUpsertBulk) ClearLastError() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UpstreamUpsertBulk) SetCreatedBy(v int64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UpstreamUpsertBulk) AddCreatedBy(v int64) *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UpstreamUpsertBulk) UpdateCreatedBy() *UpstreamUpsertBulk {
	return u.Update(func(s *UpstreamUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *UpstreamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
