// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresource"
)

// UpstreamResourceUpdate is the builder for updating UpstreamResource entities.
type UpstreamResourceUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamResourceMutation
}

// Where appends a list predicates to the UpstreamResourceUpdate builder.
func (_u *UpstreamResourceUpdate) Where(ps ...predicate.UpstreamResource) *UpstreamResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamResourceUpdate) SetUpdatedAt(v time.Time) *UpstreamResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamResourceUpdate) SetDeletedAt(v time.Time) *UpstreamResourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamResourceUpdate) ClearDeletedAt() *UpstreamResourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpstreamID sets the "upstream_id" field.
func (_u *UpstreamResourceUpdate) SetUpstreamID(v int64) *UpstreamResourceUpdate {
	_u.mutation.ResetUpstreamID()
	_u.mutation.SetUpstreamID(v)
	return _u
}

// SetNillableUpstreamID sets the "upstream_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableUpstreamID(v *int64) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetUpstreamID(*v)
	}
	return _u
}

// AddUpstreamID adds value to the "upstream_id" field.
func (_u *UpstreamResourceUpdate) AddUpstreamID(v int64) *UpstreamResourceUpdate {
	_u.mutation.AddUpstreamID(v)
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UpstreamResourceUpdate) SetResourceType(v string) *UpstreamResourceUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableResourceType(v *string) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamResourceUpdate) SetRemoteID(v string) *UpstreamResourceUpdate {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableRemoteID(v *string) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamResourceUpdate) SetName(v string) *UpstreamResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableName(v *string) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *UpstreamResourceUpdate) SetGroupName(v string) *UpstreamResourceUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableGroupName(v *string) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *UpstreamResourceUpdate) ClearGroupName() *UpstreamResourceUpdate {
	_u.mutation.ClearGroupName()
	return _u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_u *UpstreamResourceUpdate) SetKeyEncrypted(v string) *UpstreamResourceUpdate {
	_u.mutation.SetKeyEncrypted(v)
	return _u
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableKeyEncrypted(v *string) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetKeyEncrypted(*v)
	}
	return _u
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (_u *UpstreamResourceUpdate) SetModelsSnapshot(v []string) *UpstreamResourceUpdate {
	_u.mutation.SetModelsSnapshot(v)
	return _u
}

// AppendModelsSnapshot appends value to the "models_snapshot" field.
func (_u *UpstreamResourceUpdate) AppendModelsSnapshot(v []string) *UpstreamResourceUpdate {
	_u.mutation.AppendModelsSnapshot(v)
	return _u
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (_u *UpstreamResourceUpdate) SetModelsFetchedAt(v time.Time) *UpstreamResourceUpdate {
	_u.mutation.SetModelsFetchedAt(v)
	return _u
}

// SetNillableModelsFetchedAt sets the "models_fetched_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableModelsFetchedAt(v *time.Time) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetModelsFetchedAt(*v)
	}
	return _u
}

// ClearModelsFetchedAt clears the value of the "models_fetched_at" field.
func (_u *UpstreamResourceUpdate) ClearModelsFetchedAt() *UpstreamResourceUpdate {
	_u.mutation.ClearModelsFetchedAt()
	return _u
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (_u *UpstreamResourceUpdate) SetSyncedAccountID(v int64) *UpstreamResourceUpdate {
	_u.mutation.ResetSyncedAccountID()
	_u.mutation.SetSyncedAccountID(v)
	return _u
}

// SetNillableSyncedAccountID sets the "synced_account_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableSyncedAccountID(v *int64) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetSyncedAccountID(*v)
	}
	return _u
}

// AddSyncedAccountID adds value to the "synced_account_id" field.
func (_u *UpstreamResourceUpdate) AddSyncedAccountID(v int64) *UpstreamResourceUpdate {
	_u.mutation.AddSyncedAccountID(v)
	return _u
}

// ClearSyncedAccountID clears the value of the "synced_account_id" field.
func (_u *UpstreamResourceUpdate) ClearSyncedAccountID() *UpstreamResourceUpdate {
	_u.mutation.ClearSyncedAccountID()
	return _u
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdate) SetSyncedRateMultiplier(v float64) *UpstreamResourceUpdate {
	_u.mutation.ResetSyncedRateMultiplier()
	_u.mutation.SetSyncedRateMultiplier(v)
	return _u
}

// SetNillableSyncedRateMultiplier sets the "synced_rate_multiplier" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableSyncedRateMultiplier(v *float64) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetSyncedRateMultiplier(*v)
	}
	return _u
}

// AddSyncedRateMultiplier adds value to the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdate) AddSyncedRateMultiplier(v float64) *UpstreamResourceUpdate {
	_u.mutation.AddSyncedRateMultiplier(v)
	return _u
}

// ClearSyncedRateMultiplier clears the value of the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdate) ClearSyncedRateMultiplier() *UpstreamResourceUpdate {
	_u.mutation.ClearSyncedRateMultiplier()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UpstreamResourceUpdate) SetSyncedAt(v time.Time) *UpstreamResourceUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableSyncedAt(v *time.Time) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *UpstreamResourceUpdate) ClearSyncedAt() *UpstreamResourceUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamResourceUpdate) SetEnabled(v bool) *UpstreamResourceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamResourceUpdate) SetNillableEnabled(v *bool) *UpstreamResourceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the UpstreamResourceMutation object of the builder.
func (_u *UpstreamResourceUpdate) Mutation() *UpstreamResourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamResourceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamResourceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamresource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamresource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamresource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamResourceUpdate) check() error {
	if v, ok := _u.mutation.UpstreamID(); ok {
		if err := upstreamresource.UpstreamIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.upstream_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := upstreamresource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamresource.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamresource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := upstreamresource.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.group_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamresource.Table, upstreamresource.Columns, sqlgraph.NewFieldSpec(upstreamresource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamresource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamresource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamresource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpstreamID(); ok {
		_spec.SetField(upstreamresource.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamID(); ok {
		_spec.AddField(upstreamresource.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(upstreamresource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamresource.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamresource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(upstreamresource.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(upstreamresource.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.KeyEncrypted(); ok {
		_spec.SetField(upstreamresource.FieldKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelsSnapshot(); ok {
		_spec.SetField(upstreamresource.FieldModelsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstreamresource.FieldModelsSnapshot, value)
		})
	}
	if value, ok := _u.mutation.ModelsFetchedAt(); ok {
		_spec.SetField(upstreamresource.FieldModelsFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.ModelsFetchedAtCleared() {
		_spec.ClearField(upstreamresource.FieldModelsFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncedAccountID(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncedAccountID(); ok {
		_spec.AddField(upstreamresource.FieldSyncedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.SyncedAccountIDCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SyncedRateMultiplier(); ok {
		_spec.SetField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSyncedRateMultiplier(); ok {
		_spec.AddField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.SyncedRateMultiplierCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamresource.FieldEnabled, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamResourceUpdateOne is the builder for updating a single UpstreamResource entity.
type UpstreamResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamResourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamResourceUpdateOne) SetUpdatedAt(v time.Time) *UpstreamResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamResourceUpdateOne) SetDeletedAt(v time.Time) *UpstreamResourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamResourceUpdateOne) ClearDeletedAt() *UpstreamResourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUpstreamID sets the "upstream_id" field.
func (_u *UpstreamResourceUpdateOne) SetUpstreamID(v int64) *UpstreamResourceUpdateOne {
	_u.mutation.ResetUpstreamID()
	_u.mutation.SetUpstreamID(v)
	return _u
}

// SetNillableUpstreamID sets the "upstream_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableUpstreamID(v *int64) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetUpstreamID(*v)
	}
	return _u
}

// AddUpstreamID adds value to the "upstream_id" field.
func (_u *UpstreamResourceUpdateOne) AddUpstreamID(v int64) *UpstreamResourceUpdateOne {
	_u.mutation.AddUpstreamID(v)
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *UpstreamResourceUpdateOne) SetResourceType(v string) *UpstreamResourceUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableResourceType(v *string) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetRemoteID sets the "remote_id" field.
func (_u *UpstreamResourceUpdateOne) SetRemoteID(v string) *UpstreamResourceUpdateOne {
	_u.mutation.SetRemoteID(v)
	return _u
}

// SetNillableRemoteID sets the "remote_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableRemoteID(v *string) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetRemoteID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamResourceUpdateOne) SetName(v string) *UpstreamResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableName(v *string) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *UpstreamResourceUpdateOne) SetGroupName(v string) *UpstreamResourceUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableGroupName(v *string) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *UpstreamResourceUpdateOne) ClearGroupName() *UpstreamResourceUpdateOne {
	_u.mutation.ClearGroupName()
	return _u
}

// SetKeyEncrypted sets the "key_encrypted" field.
func (_u *UpstreamResourceUpdateOne) SetKeyEncrypted(v string) *UpstreamResourceUpdateOne {
	_u.mutation.SetKeyEncrypted(v)
	return _u
}

// SetNillableKeyEncrypted sets the "key_encrypted" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableKeyEncrypted(v *string) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetKeyEncrypted(*v)
	}
	return _u
}

// SetModelsSnapshot sets the "models_snapshot" field.
func (_u *UpstreamResourceUpdateOne) SetModelsSnapshot(v []string) *UpstreamResourceUpdateOne {
	_u.mutation.SetModelsSnapshot(v)
	return _u
}

// AppendModelsSnapshot appends value to the "models_snapshot" field.
func (_u *UpstreamResourceUpdateOne) AppendModelsSnapshot(v []string) *UpstreamResourceUpdateOne {
	_u.mutation.AppendModelsSnapshot(v)
	return _u
}

// SetModelsFetchedAt sets the "models_fetched_at" field.
func (_u *UpstreamResourceUpdateOne) SetModelsFetchedAt(v time.Time) *UpstreamResourceUpdateOne {
	_u.mutation.SetModelsFetchedAt(v)
	return _u
}

// SetNillableModelsFetchedAt sets the "models_fetched_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableModelsFetchedAt(v *time.Time) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetModelsFetchedAt(*v)
	}
	return _u
}

// ClearModelsFetchedAt clears the value of the "models_fetched_at" field.
func (_u *UpstreamResourceUpdateOne) ClearModelsFetchedAt() *UpstreamResourceUpdateOne {
	_u.mutation.ClearModelsFetchedAt()
	return _u
}

// SetSyncedAccountID sets the "synced_account_id" field.
func (_u *UpstreamResourceUpdateOne) SetSyncedAccountID(v int64) *UpstreamResourceUpdateOne {
	_u.mutation.ResetSyncedAccountID()
	_u.mutation.SetSyncedAccountID(v)
	return _u
}

// SetNillableSyncedAccountID sets the "synced_account_id" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableSyncedAccountID(v *int64) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetSyncedAccountID(*v)
	}
	return _u
}

// AddSyncedAccountID adds value to the "synced_account_id" field.
func (_u *UpstreamResourceUpdateOne) AddSyncedAccountID(v int64) *UpstreamResourceUpdateOne {
	_u.mutation.AddSyncedAccountID(v)
	return _u
}

// ClearSyncedAccountID clears the value of the "synced_account_id" field.
func (_u *UpstreamResourceUpdateOne) ClearSyncedAccountID() *UpstreamResourceUpdateOne {
	_u.mutation.ClearSyncedAccountID()
	return _u
}

// SetSyncedRateMultiplier sets the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdateOne) SetSyncedRateMultiplier(v float64) *UpstreamResourceUpdateOne {
	_u.mutation.ResetSyncedRateMultiplier()
	_u.mutation.SetSyncedRateMultiplier(v)
	return _u
}

// SetNillableSyncedRateMultiplier sets the "synced_rate_multiplier" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableSyncedRateMultiplier(v *float64) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetSyncedRateMultiplier(*v)
	}
	return _u
}

// AddSyncedRateMultiplier adds value to the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdateOne) AddSyncedRateMultiplier(v float64) *UpstreamResourceUpdateOne {
	_u.mutation.AddSyncedRateMultiplier(v)
	return _u
}

// ClearSyncedRateMultiplier clears the value of the "synced_rate_multiplier" field.
func (_u *UpstreamResourceUpdateOne) ClearSyncedRateMultiplier() *UpstreamResourceUpdateOne {
	_u.mutation.ClearSyncedRateMultiplier()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UpstreamResourceUpdateOne) SetSyncedAt(v time.Time) *UpstreamResourceUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableSyncedAt(v *time.Time) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *UpstreamResourceUpdateOne) ClearSyncedAt() *UpstreamResourceUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamResourceUpdateOne) SetEnabled(v bool) *UpstreamResourceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamResourceUpdateOne) SetNillableEnabled(v *bool) *UpstreamResourceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the UpstreamResourceMutation object of the builder.
func (_u *UpstreamResourceUpdateOne) Mutation() *UpstreamResourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamResourceUpdate builder.
func (_u *UpstreamResourceUpdateOne) Where(ps ...predicate.UpstreamResource) *UpstreamResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamResourceUpdateOne) Select(field string, fields ...string) *UpstreamResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamResource entity.
func (_u *UpstreamResourceUpdateOne) Save(ctx context.Context) (*UpstreamResource, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamResourceUpdateOne) SaveX(ctx context.Context) *UpstreamResource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamResourceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamresource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamresource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamresource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamResourceUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamID(); ok {
		if err := upstreamresource.UpstreamIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.upstream_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := upstreamresource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteID(); ok {
		if err := upstreamresource.RemoteIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.remote_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamresource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := upstreamresource.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamResource.group_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamResourceUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamResource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamresource.Table, upstreamresource.Columns, sqlgraph.NewFieldSpec(upstreamresource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamResource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamresource.FieldID)
		for _, f := range fields {
			if !upstreamresource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamresource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamresource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamresource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamresource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpstreamID(); ok {
		_spec.SetField(upstreamresource.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamID(); ok {
		_spec.AddField(upstreamresource.FieldUpstreamID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(upstreamresource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteID(); ok {
		_spec.SetField(upstreamresource.FieldRemoteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamresource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(upstreamresource.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(upstreamresource.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.KeyEncrypted(); ok {
		_spec.SetField(upstreamresource.FieldKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelsSnapshot(); ok {
		_spec.SetField(upstreamresource.FieldModelsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstreamresource.FieldModelsSnapshot, value)
		})
	}
	if value, ok := _u.mutation.ModelsFetchedAt(); ok {
		_spec.SetField(upstreamresource.FieldModelsFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.ModelsFetchedAtCleared() {
		_spec.ClearField(upstreamresource.FieldModelsFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SyncedAccountID(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSyncedAccountID(); ok {
		_spec.AddField(upstreamresource.FieldSyncedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.SyncedAccountIDCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SyncedRateMultiplier(); ok {
		_spec.SetField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSyncedRateMultiplier(); ok {
		_spec.AddField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.SyncedRateMultiplierCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedRateMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamresource.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(upstreamresource.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamresource.FieldEnabled, field.TypeBool, value)
	}
	_node = &UpstreamResource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamresource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
