// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamresourceaccount"
)

// UpstreamResourceAccount is the model entity for the UpstreamResourceAccount schema.
type UpstreamResourceAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID int64 `json:"resource_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt     time.Time `json:"synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamResourceAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamresourceaccount.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case upstreamresourceaccount.FieldID, upstreamresourceaccount.FieldResourceID, upstreamresourceaccount.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case upstreamresourceaccount.FieldPlatform:
			values[i] = new(sql.NullString)
		case upstreamresourceaccount.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamResourceAccount fields.
func (_m *UpstreamResourceAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamresourceaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamresourceaccount.FieldResourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.Int64
			}
		case upstreamresourceaccount.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case upstreamresourceaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case upstreamresourceaccount.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case upstreamresourceaccount.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamResourceAccount.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamResourceAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamResourceAccount.
// Note that you need to call UpstreamResourceAccount.Unwrap() before calling this method if this UpstreamResourceAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamResourceAccount) Update() *UpstreamResourceAccountUpdateOne {
	return NewUpstreamResourceAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamResourceAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamResourceAccount) Unwrap() *UpstreamResourceAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamResourceAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamResourceAccount) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamResourceAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamResourceAccounts is a parsable slice of UpstreamResourceAccount.
type UpstreamResourceAccounts []*UpstreamResourceAccount
