// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstream"
)

// UpstreamUpdate is the builder for updating Upstream entities.
type UpstreamUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamMutation
}

// Where appends a list predicates to the UpstreamUpdate builder.
func (_u *UpstreamUpdate) Where(ps ...predicate.Upstream) *UpstreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUpdate) SetUpdatedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamUpdate) SetDeletedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamUpdate) ClearDeletedAt() *UpstreamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamUpdate) SetName(v string) *UpstreamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableName(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortCode sets the "sort_code" field.
func (_u *UpstreamUpdate) SetSortCode(v int) *UpstreamUpdate {
	_u.mutation.ResetSortCode()
	_u.mutation.SetSortCode(v)
	return _u
}

// SetNillableSortCode sets the "sort_code" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableSortCode(v *int) *UpstreamUpdate {
	if v != nil {
		_u.SetSortCode(*v)
	}
	return _u
}

// AddSortCode adds value to the "sort_code" field.
func (_u *UpstreamUpdate) AddSortCode(v int) *UpstreamUpdate {
	_u.mutation.AddSortCode(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *UpstreamUpdate) SetKind(v string) *UpstreamUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableKind(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamUpdate) SetBaseURL(v string) *UpstreamUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableBaseURL(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *UpstreamUpdate) SetTokenEncrypted(v string) *UpstreamUpdate {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// SetNillableTokenEncrypted sets the "token_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableTokenEncrypted(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetTokenEncrypted(*v)
	}
	return _u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_u *UpstreamUpdate) SetRefreshTokenEncrypted(v string) *UpstreamUpdate {
	_u.mutation.SetRefreshTokenEncrypted(v)
	return _u
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableRefreshTokenEncrypted(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetRefreshTokenEncrypted(*v)
	}
	return _u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (_u *UpstreamUpdate) ClearRefreshTokenEncrypted() *UpstreamUpdate {
	_u.mutation.ClearRefreshTokenEncrypted()
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *UpstreamUpdate) SetPasswordEncrypted(v string) *UpstreamUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillablePasswordEncrypted(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (_u *UpstreamUpdate) ClearPasswordEncrypted() *UpstreamUpdate {
	_u.mutation.ClearPasswordEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamUpdate) SetTokenExpiresAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableTokenExpiresAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamUpdate) ClearTokenExpiresAt() *UpstreamUpdate {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetLoginIdentifier sets the "login_identifier" field.
func (_u *UpstreamUpdate) SetLoginIdentifier(v string) *UpstreamUpdate {
	_u.mutation.SetLoginIdentifier(v)
	return _u
}

// SetNillableLoginIdentifier sets the "login_identifier" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableLoginIdentifier(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetLoginIdentifier(*v)
	}
	return _u
}

// ClearLoginIdentifier clears the value of the "login_identifier" field.
func (_u *UpstreamUpdate) ClearLoginIdentifier() *UpstreamUpdate {
	_u.mutation.ClearLoginIdentifier()
	return _u
}

// SetRemoteUserID sets the "remote_user_id" field.
func (_u *UpstreamUpdate) SetRemoteUserID(v string) *UpstreamUpdate {
	_u.mutation.SetRemoteUserID(v)
	return _u
}

// SetNillableRemoteUserID sets the "remote_user_id" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableRemoteUserID(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetRemoteUserID(*v)
	}
	return _u
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (_u *UpstreamUpdate) ClearRemoteUserID() *UpstreamUpdate {
	_u.mutation.ClearRemoteUserID()
	return _u
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (_u *UpstreamUpdate) SetBalanceSnapshot(v map[string]interface{}) *UpstreamUpdate {
	_u.mutation.SetBalanceSnapshot(v)
	return _u
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (_u *UpstreamUpdate) SetGroupSnapshot(v map[string]interface{}) *UpstreamUpdate {
	_u.mutation.SetGroupSnapshot(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UpstreamUpdate) SetNotes(v string) *UpstreamUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableNotes(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UpstreamUpdate) ClearNotes() *UpstreamUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamUpdate) SetEnabled(v bool) *UpstreamUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableEnabled(v *bool) *UpstreamUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *UpstreamUpdate) SetLastCheckedAt(v time.Time) *UpstreamUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableLastCheckedAt(v *time.Time) *UpstreamUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *UpstreamUpdate) ClearLastCheckedAt() *UpstreamUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamUpdate) SetLastError(v string) *UpstreamUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableLastError(v *string) *UpstreamUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *UpstreamUpdate) ClearLastError() *UpstreamUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UpstreamUpdate) SetCreatedBy(v int64) *UpstreamUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UpstreamUpdate) SetNillableCreatedBy(v *int64) *UpstreamUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UpstreamUpdate) AddCreatedBy(v int64) *UpstreamUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the UpstreamMutation object of the builder.
func (_u *UpstreamUpdate) Mutation() *UpstreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := upstream.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Upstream.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginIdentifier(); ok {
		if err := upstream.LoginIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "login_identifier", err: fmt.Errorf(`ent: validator failed for field "Upstream.login_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteUserID(); ok {
		if err := upstream.RemoteUserIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_user_id", err: fmt.Errorf(`ent: validator failed for field "Upstream.remote_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstream.Table, upstream.Columns, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortCode(); ok {
		_spec.SetField(upstream.FieldSortCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortCode(); ok {
		_spec.AddField(upstream.FieldSortCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(upstream.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(upstream.FieldTokenEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstream.FieldRefreshTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenEncryptedCleared() {
		_spec.ClearField(upstream.FieldRefreshTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(upstream.FieldPasswordEncrypted, field.TypeString, value)
	}
	if _u.mutation.PasswordEncryptedCleared() {
		_spec.ClearField(upstream.FieldPasswordEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstream.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstream.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LoginIdentifier(); ok {
		_spec.SetField(upstream.FieldLoginIdentifier, field.TypeString, value)
	}
	if _u.mutation.LoginIdentifierCleared() {
		_spec.ClearField(upstream.FieldLoginIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteUserID(); ok {
		_spec.SetField(upstream.FieldRemoteUserID, field.TypeString, value)
	}
	if _u.mutation.RemoteUserIDCleared() {
		_spec.ClearField(upstream.FieldRemoteUserID, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceSnapshot(); ok {
		_spec.SetField(upstream.FieldBalanceSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.GroupSnapshot(); ok {
		_spec.SetField(upstream.FieldGroupSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(upstream.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(upstream.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstream.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(upstream.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(upstream.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstream.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(upstream.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(upstream.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(upstream.FieldCreatedBy, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamUpdateOne is the builder for updating a single Upstream entity.
type UpstreamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUpdateOne) SetUpdatedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamUpdateOne) SetDeletedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamUpdateOne) ClearDeletedAt() *UpstreamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamUpdateOne) SetName(v string) *UpstreamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableName(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortCode sets the "sort_code" field.
func (_u *UpstreamUpdateOne) SetSortCode(v int) *UpstreamUpdateOne {
	_u.mutation.ResetSortCode()
	_u.mutation.SetSortCode(v)
	return _u
}

// SetNillableSortCode sets the "sort_code" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableSortCode(v *int) *UpstreamUpdateOne {
	if v != nil {
		_u.SetSortCode(*v)
	}
	return _u
}

// AddSortCode adds value to the "sort_code" field.
func (_u *UpstreamUpdateOne) AddSortCode(v int) *UpstreamUpdateOne {
	_u.mutation.AddSortCode(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *UpstreamUpdateOne) SetKind(v string) *UpstreamUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableKind(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamUpdateOne) SetBaseURL(v string) *UpstreamUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableBaseURL(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *UpstreamUpdateOne) SetTokenEncrypted(v string) *UpstreamUpdateOne {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// SetNillableTokenEncrypted sets the "token_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableTokenEncrypted(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetTokenEncrypted(*v)
	}
	return _u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_u *UpstreamUpdateOne) SetRefreshTokenEncrypted(v string) *UpstreamUpdateOne {
	_u.mutation.SetRefreshTokenEncrypted(v)
	return _u
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableRefreshTokenEncrypted(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetRefreshTokenEncrypted(*v)
	}
	return _u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (_u *UpstreamUpdateOne) ClearRefreshTokenEncrypted() *UpstreamUpdateOne {
	_u.mutation.ClearRefreshTokenEncrypted()
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *UpstreamUpdateOne) SetPasswordEncrypted(v string) *UpstreamUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillablePasswordEncrypted(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (_u *UpstreamUpdateOne) ClearPasswordEncrypted() *UpstreamUpdateOne {
	_u.mutation.ClearPasswordEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamUpdateOne) SetTokenExpiresAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableTokenExpiresAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamUpdateOne) ClearTokenExpiresAt() *UpstreamUpdateOne {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetLoginIdentifier sets the "login_identifier" field.
func (_u *UpstreamUpdateOne) SetLoginIdentifier(v string) *UpstreamUpdateOne {
	_u.mutation.SetLoginIdentifier(v)
	return _u
}

// SetNillableLoginIdentifier sets the "login_identifier" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableLoginIdentifier(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetLoginIdentifier(*v)
	}
	return _u
}

// ClearLoginIdentifier clears the value of the "login_identifier" field.
func (_u *UpstreamUpdateOne) ClearLoginIdentifier() *UpstreamUpdateOne {
	_u.mutation.ClearLoginIdentifier()
	return _u
}

// SetRemoteUserID sets the "remote_user_id" field.
func (_u *UpstreamUpdateOne) SetRemoteUserID(v string) *UpstreamUpdateOne {
	_u.mutation.SetRemoteUserID(v)
	return _u
}

// SetNillableRemoteUserID sets the "remote_user_id" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableRemoteUserID(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetRemoteUserID(*v)
	}
	return _u
}

// ClearRemoteUserID clears the value of the "remote_user_id" field.
func (_u *UpstreamUpdateOne) ClearRemoteUserID() *UpstreamUpdateOne {
	_u.mutation.ClearRemoteUserID()
	return _u
}

// SetBalanceSnapshot sets the "balance_snapshot" field.
func (_u *UpstreamUpdateOne) SetBalanceSnapshot(v map[string]interface{}) *UpstreamUpdateOne {
	_u.mutation.SetBalanceSnapshot(v)
	return _u
}

// SetGroupSnapshot sets the "group_snapshot" field.
func (_u *UpstreamUpdateOne) SetGroupSnapshot(v map[string]interface{}) *UpstreamUpdateOne {
	_u.mutation.SetGroupSnapshot(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UpstreamUpdateOne) SetNotes(v string) *UpstreamUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableNotes(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UpstreamUpdateOne) ClearNotes() *UpstreamUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamUpdateOne) SetEnabled(v bool) *UpstreamUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableEnabled(v *bool) *UpstreamUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *UpstreamUpdateOne) SetLastCheckedAt(v time.Time) *UpstreamUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableLastCheckedAt(v *time.Time) *UpstreamUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *UpstreamUpdateOne) ClearLastCheckedAt() *UpstreamUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamUpdateOne) SetLastError(v string) *UpstreamUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableLastError(v *string) *UpstreamUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *UpstreamUpdateOne) ClearLastError() *UpstreamUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UpstreamUpdateOne) SetCreatedBy(v int64) *UpstreamUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UpstreamUpdateOne) SetNillableCreatedBy(v *int64) *UpstreamUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *UpstreamUpdateOne) AddCreatedBy(v int64) *UpstreamUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the UpstreamMutation object of the builder.
func (_u *UpstreamUpdateOne) Mutation() *UpstreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamUpdate builder.
func (_u *UpstreamUpdateOne) Where(ps ...predicate.Upstream) *UpstreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamUpdateOne) Select(field string, fields ...string) *UpstreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Upstream entity.
func (_u *UpstreamUpdateOne) Save(ctx context.Context) (*Upstream, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUpdateOne) SaveX(ctx context.Context) *Upstream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Upstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := upstream.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Upstream.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Upstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginIdentifier(); ok {
		if err := upstream.LoginIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "login_identifier", err: fmt.Errorf(`ent: validator failed for field "Upstream.login_identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteUserID(); ok {
		if err := upstream.RemoteUserIDValidator(v); err != nil {
			return &ValidationError{Name: "remote_user_id", err: fmt.Errorf(`ent: validator failed for field "Upstream.remote_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUpdateOne) sqlSave(ctx context.Context) (_node *Upstream, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstream.Table, upstream.Columns, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upstream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstream.FieldID)
		for _, f := range fields {
			if !upstream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortCode(); ok {
		_spec.SetField(upstream.FieldSortCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortCode(); ok {
		_spec.AddField(upstream.FieldSortCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(upstream.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(upstream.FieldTokenEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstream.FieldRefreshTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenEncryptedCleared() {
		_spec.ClearField(upstream.FieldRefreshTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(upstream.FieldPasswordEncrypted, field.TypeString, value)
	}
	if _u.mutation.PasswordEncryptedCleared() {
		_spec.ClearField(upstream.FieldPasswordEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstream.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstream.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LoginIdentifier(); ok {
		_spec.SetField(upstream.FieldLoginIdentifier, field.TypeString, value)
	}
	if _u.mutation.LoginIdentifierCleared() {
		_spec.ClearField(upstream.FieldLoginIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteUserID(); ok {
		_spec.SetField(upstream.FieldRemoteUserID, field.TypeString, value)
	}
	if _u.mutation.RemoteUserIDCleared() {
		_spec.ClearField(upstream.FieldRemoteUserID, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceSnapshot(); ok {
		_spec.SetField(upstream.FieldBalanceSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.GroupSnapshot(); ok {
		_spec.SetField(upstream.FieldGroupSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(upstream.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(upstream.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstream.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(upstream.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(upstream.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstream.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(upstream.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(upstream.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(upstream.FieldCreatedBy, field.TypeInt64, value)
	}
	_node = &Upstream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
