// Code generated by ent, DO NOT EDIT.

package upstreamresource

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamresource type in the database.
	Label = "upstream_resource"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldRemoteID holds the string denoting the remote_id field in the database.
	FieldRemoteID = "remote_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldKeyEncrypted holds the string denoting the key_encrypted field in the database.
	FieldKeyEncrypted = "key_encrypted"
	// FieldModelsSnapshot holds the string denoting the models_snapshot field in the database.
	FieldModelsSnapshot = "models_snapshot"
	// FieldModelsFetchedAt holds the string denoting the models_fetched_at field in the database.
	FieldModelsFetchedAt = "models_fetched_at"
	// FieldSyncedAccountID holds the string denoting the synced_account_id field in the database.
	FieldSyncedAccountID = "synced_account_id"
	// FieldSyncedRateMultiplier holds the string denoting the synced_rate_multiplier field in the database.
	FieldSyncedRateMultiplier = "synced_rate_multiplier"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the upstreamresource in the database.
	Table = "upstream_resources"
)

// Columns holds all SQL columns for upstreamresource fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUpstreamID,
	FieldResourceType,
	FieldRemoteID,
	FieldName,
	FieldGroupName,
	FieldKeyEncrypted,
	FieldModelsSnapshot,
	FieldModelsFetchedAt,
	FieldSyncedAccountID,
	FieldSyncedRateMultiplier,
	FieldSyncedAt,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UpstreamIDValidator is a validator for the "upstream_id" field. It is called by the builders before save.
	UpstreamIDValidator func(int64) error
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// RemoteIDValidator is a validator for the "remote_id" field. It is called by the builders before save.
	RemoteIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// DefaultModelsSnapshot holds the default value on creation for the "models_snapshot" field.
	DefaultModelsSnapshot []string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the UpstreamResource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByRemoteID orders the results by the remote_id field.
func ByRemoteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByKeyEncrypted orders the results by the key_encrypted field.
func ByKeyEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyEncrypted, opts...).ToFunc()
}

// ByModelsFetchedAt orders the results by the models_fetched_at field.
func ByModelsFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelsFetchedAt, opts...).ToFunc()
}

// BySyncedAccountID orders the results by the synced_account_id field.
func BySyncedAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAccountID, opts...).ToFunc()
}

// BySyncedRateMultiplier orders the results by the synced_rate_multiplier field.
func BySyncedRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedRateMultiplier, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
