// Code generated by ent, DO NOT EDIT.

package upstreamresource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldDeletedAt, v))
}

// UpstreamID applies equality check predicate on the "upstream_id" field. It's identical to UpstreamIDEQ.
func UpstreamID(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldUpstreamID, v))
}

// ResourceType applies equality check predicate on the "resource_type" field. It's identical to ResourceTypeEQ.
func ResourceType(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldResourceType, v))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldRemoteID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldName, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldGroupName, v))
}

// KeyEncrypted applies equality check predicate on the "key_encrypted" field. It's identical to KeyEncryptedEQ.
func KeyEncrypted(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldKeyEncrypted, v))
}

// ModelsFetchedAt applies equality check predicate on the "models_fetched_at" field. It's identical to ModelsFetchedAtEQ.
func ModelsFetchedAt(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldModelsFetchedAt, v))
}

// SyncedAccountID applies equality check predicate on the "synced_account_id" field. It's identical to SyncedAccountIDEQ.
func SyncedAccountID(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedAccountID, v))
}

// SyncedRateMultiplier applies equality check predicate on the "synced_rate_multiplier" field. It's identical to SyncedRateMultiplierEQ.
func SyncedRateMultiplier(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedRateMultiplier, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedAt, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldDeletedAt))
}

// UpstreamIDEQ applies the EQ predicate on the "upstream_id" field.
func UpstreamIDEQ(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldUpstreamID, v))
}

// UpstreamIDNEQ applies the NEQ predicate on the "upstream_id" field.
func UpstreamIDNEQ(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldUpstreamID, v))
}

// UpstreamIDIn applies the In predicate on the "upstream_id" field.
func UpstreamIDIn(vs ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldUpstreamID, vs...))
}

// UpstreamIDNotIn applies the NotIn predicate on the "upstream_id" field.
func UpstreamIDNotIn(vs ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldUpstreamID, vs...))
}

// UpstreamIDGT applies the GT predicate on the "upstream_id" field.
func UpstreamIDGT(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldUpstreamID, v))
}

// UpstreamIDGTE applies the GTE predicate on the "upstream_id" field.
func UpstreamIDGTE(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldUpstreamID, v))
}

// UpstreamIDLT applies the LT predicate on the "upstream_id" field.
func UpstreamIDLT(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldUpstreamID, v))
}

// UpstreamIDLTE applies the LTE predicate on the "upstream_id" field.
func UpstreamIDLTE(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldUpstreamID, v))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceTypeGT applies the GT predicate on the "resource_type" field.
func ResourceTypeGT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldResourceType, v))
}

// ResourceTypeGTE applies the GTE predicate on the "resource_type" field.
func ResourceTypeGTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldResourceType, v))
}

// ResourceTypeLT applies the LT predicate on the "resource_type" field.
func ResourceTypeLT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldResourceType, v))
}

// ResourceTypeLTE applies the LTE predicate on the "resource_type" field.
func ResourceTypeLTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldResourceType, v))
}

// ResourceTypeContains applies the Contains predicate on the "resource_type" field.
func ResourceTypeContains(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContains(FieldResourceType, v))
}

// ResourceTypeHasPrefix applies the HasPrefix predicate on the "resource_type" field.
func ResourceTypeHasPrefix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasPrefix(FieldResourceType, v))
}

// ResourceTypeHasSuffix applies the HasSuffix predicate on the "resource_type" field.
func ResourceTypeHasSuffix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasSuffix(FieldResourceType, v))
}

// ResourceTypeEqualFold applies the EqualFold predicate on the "resource_type" field.
func ResourceTypeEqualFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEqualFold(FieldResourceType, v))
}

// ResourceTypeContainsFold applies the ContainsFold predicate on the "resource_type" field.
func ResourceTypeContainsFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContainsFold(FieldResourceType, v))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContainsFold(FieldRemoteID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContainsFold(FieldName, v))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameIsNil applies the IsNil predicate on the "group_name" field.
func GroupNameIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldGroupName))
}

// GroupNameNotNil applies the NotNil predicate on the "group_name" field.
func GroupNameNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldGroupName))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContainsFold(FieldGroupName, v))
}

// KeyEncryptedEQ applies the EQ predicate on the "key_encrypted" field.
func KeyEncryptedEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedNEQ applies the NEQ predicate on the "key_encrypted" field.
func KeyEncryptedNEQ(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedIn applies the In predicate on the "key_encrypted" field.
func KeyEncryptedIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedNotIn applies the NotIn predicate on the "key_encrypted" field.
func KeyEncryptedNotIn(vs ...string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedGT applies the GT predicate on the "key_encrypted" field.
func KeyEncryptedGT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldKeyEncrypted, v))
}

// KeyEncryptedGTE applies the GTE predicate on the "key_encrypted" field.
func KeyEncryptedGTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldKeyEncrypted, v))
}

// KeyEncryptedLT applies the LT predicate on the "key_encrypted" field.
func KeyEncryptedLT(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldKeyEncrypted, v))
}

// KeyEncryptedLTE applies the LTE predicate on the "key_encrypted" field.
func KeyEncryptedLTE(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldKeyEncrypted, v))
}

// KeyEncryptedContains applies the Contains predicate on the "key_encrypted" field.
func KeyEncryptedContains(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContains(FieldKeyEncrypted, v))
}

// KeyEncryptedHasPrefix applies the HasPrefix predicate on the "key_encrypted" field.
func KeyEncryptedHasPrefix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasPrefix(FieldKeyEncrypted, v))
}

// KeyEncryptedHasSuffix applies the HasSuffix predicate on the "key_encrypted" field.
func KeyEncryptedHasSuffix(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldHasSuffix(FieldKeyEncrypted, v))
}

// KeyEncryptedEqualFold applies the EqualFold predicate on the "key_encrypted" field.
func KeyEncryptedEqualFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEqualFold(FieldKeyEncrypted, v))
}

// KeyEncryptedContainsFold applies the ContainsFold predicate on the "key_encrypted" field.
func KeyEncryptedContainsFold(v string) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldContainsFold(FieldKeyEncrypted, v))
}

// ModelsFetchedAtEQ applies the EQ predicate on the "models_fetched_at" field.
func ModelsFetchedAtEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtNEQ applies the NEQ predicate on the "models_fetched_at" field.
func ModelsFetchedAtNEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtIn applies the In predicate on the "models_fetched_at" field.
func ModelsFetchedAtIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldModelsFetchedAt, vs...))
}

// ModelsFetchedAtNotIn applies the NotIn predicate on the "models_fetched_at" field.
func ModelsFetchedAtNotIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldModelsFetchedAt, vs...))
}

// ModelsFetchedAtGT applies the GT predicate on the "models_fetched_at" field.
func ModelsFetchedAtGT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtGTE applies the GTE predicate on the "models_fetched_at" field.
func ModelsFetchedAtGTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtLT applies the LT predicate on the "models_fetched_at" field.
func ModelsFetchedAtLT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtLTE applies the LTE predicate on the "models_fetched_at" field.
func ModelsFetchedAtLTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldModelsFetchedAt, v))
}

// ModelsFetchedAtIsNil applies the IsNil predicate on the "models_fetched_at" field.
func ModelsFetchedAtIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldModelsFetchedAt))
}

// ModelsFetchedAtNotNil applies the NotNil predicate on the "models_fetched_at" field.
func ModelsFetchedAtNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldModelsFetchedAt))
}

// SyncedAccountIDEQ applies the EQ predicate on the "synced_account_id" field.
func SyncedAccountIDEQ(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedAccountID, v))
}

// SyncedAccountIDNEQ applies the NEQ predicate on the "synced_account_id" field.
func SyncedAccountIDNEQ(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldSyncedAccountID, v))
}

// SyncedAccountIDIn applies the In predicate on the "synced_account_id" field.
func SyncedAccountIDIn(vs ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldSyncedAccountID, vs...))
}

// SyncedAccountIDNotIn applies the NotIn predicate on the "synced_account_id" field.
func SyncedAccountIDNotIn(vs ...int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldSyncedAccountID, vs...))
}

// SyncedAccountIDGT applies the GT predicate on the "synced_account_id" field.
func SyncedAccountIDGT(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldSyncedAccountID, v))
}

// SyncedAccountIDGTE applies the GTE predicate on the "synced_account_id" field.
func SyncedAccountIDGTE(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldSyncedAccountID, v))
}

// SyncedAccountIDLT applies the LT predicate on the "synced_account_id" field.
func SyncedAccountIDLT(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldSyncedAccountID, v))
}

// SyncedAccountIDLTE applies the LTE predicate on the "synced_account_id" field.
func SyncedAccountIDLTE(v int64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldSyncedAccountID, v))
}

// SyncedAccountIDIsNil applies the IsNil predicate on the "synced_account_id" field.
func SyncedAccountIDIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldSyncedAccountID))
}

// SyncedAccountIDNotNil applies the NotNil predicate on the "synced_account_id" field.
func SyncedAccountIDNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldSyncedAccountID))
}

// SyncedRateMultiplierEQ applies the EQ predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierEQ(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierNEQ applies the NEQ predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierNEQ(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierIn applies the In predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierIn(vs ...float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldSyncedRateMultiplier, vs...))
}

// SyncedRateMultiplierNotIn applies the NotIn predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierNotIn(vs ...float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldSyncedRateMultiplier, vs...))
}

// SyncedRateMultiplierGT applies the GT predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierGT(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierGTE applies the GTE predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierGTE(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierLT applies the LT predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierLT(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierLTE applies the LTE predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierLTE(v float64) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldSyncedRateMultiplier, v))
}

// SyncedRateMultiplierIsNil applies the IsNil predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldSyncedRateMultiplier))
}

// SyncedRateMultiplierNotNil applies the NotNil predicate on the "synced_rate_multiplier" field.
func SyncedRateMultiplierNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldSyncedRateMultiplier))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "synced_at" field.
func SyncedAtIsNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "synced_at" field.
func SyncedAtNotNil() predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNotNull(FieldSyncedAt))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamResource) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamResource) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamResource) predicate.UpstreamResource {
	return predicate.UpstreamResource(sql.NotPredicates(p))
}
